import { writeFileSync } from 'node:fs';
import { Rng } from '../core/rng';
import { BOSSES } from '../data/enemies';
import { TUNING } from '../data/tuning';
import { chapterState, BOSS_BONUS, REG_BONUS, fight, pickEncounter, randomParty } from '../sim/simlib';

const N = Number(process.argv[2] ?? 50);
const ITERS = Number(process.argv[3] ?? 10);
const REG_ROUNDS = [3.4, 4.0, 4.0, 4.4, 4.4, 4.6, 4.8, 5.0, 5.0, 5.0, 5.2, 5.2];
const BOSS_ROUNDS = [6, 8, 9, 10, 10, 11, 11, 12, 12, 12, 13, 14];
const REG_DAMAGE = 0.2;
const BOSS_WIN = [0.93, 0.88, 0.82, 0.78, 0.76, 0.74, 0.72, 0.72, 0.72, 0.72, 0.72, 0.72];
const REG_WIN = [0.99, 0.99, 0.98, 0.98, 0.98, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97, 0.97];
const clamp = (x: number, a: number, b: number) => Math.min(b, Math.max(a, x));

for (let ch = 1; ch <= 12; ch++) {
  const t = TUNING[ch];
  t.hp = 1; t.atk = 1; t.bossHp = 1; t.bossAtk = 1;
  let line = '';
  const hist: typeof t[] = [];
  const comps = Array.from({ length: 10 }, (_, k) => randomParty(ch, new Rng(ch * 1000 + k)));
  for (let it = 0; it < ITERS; it++) {
    const rng = new Rng(ch * 77 + it);
    let rw = 0, rh = 0, rr = 0, bw = 0, br = 0;
    for (let i = 0; i < N; i++) {
      const s = chapterState(ch, comps[i % comps.length], REG_BONUS);
      const r = fight(s, pickEncounter(ch, rng), false, 'smart', rng, 0.5, { noApply: true });
      rw += r.win ? 1 : 0; rh += r.hpLeft; rr += r.rounds;
      const s2 = chapterState(ch, comps[i % comps.length], BOSS_BONUS);
      let last;
      for (const g of BOSSES[ch]) last = fight(s2, g, true, 'smart', rng, 0.85, { noApply: true });
      bw += last!.win ? 1 : 0; br += last!.rounds;
    }
    const rounds = rr / N, dmg = 1 - rh / N, bwin = bw / N, brounds = br / N;
    const w = rw / N;
    t.hp = clamp(t.hp * Math.pow(REG_ROUNDS[ch - 1] / Math.max(0.5, rounds), 0.6), 0.2, 12);
    t.atk = clamp(t.atk * (w < REG_WIN[ch - 1] ? 0.93 : w > REG_WIN[ch - 1] + 0.02 && dmg < REG_DAMAGE ? 1.05 : 1), 0.4, 6);
    t.bossHp = clamp(t.bossHp * Math.pow(BOSS_ROUNDS[ch - 1] / Math.max(0.5, brounds), 0.6), 0.2, 12);
    t.bossAtk = clamp(t.bossAtk * clamp(1 + 0.9 * (bwin - BOSS_WIN[ch - 1]), 0.8, 1.25), 0.2, 8);
    if (it >= ITERS - 6) hist.push({ ...t });
    line = `ch${ch} it${it} reg: win ${(rw / N * 100).toFixed(0)}% rounds ${rounds.toFixed(1)} dmg ${(dmg * 100).toFixed(0)}% | boss: win ${(bwin * 100).toFixed(0)}% rounds ${brounds.toFixed(1)}`;
  }
  const gm = (k: keyof typeof t) => Math.exp(hist.reduce((x, h) => x + Math.log(h[k]), 0) / hist.length);
  t.hp = gm('hp'); t.atk = gm('atk'); t.bossHp = gm('bossHp'); t.bossAtk = gm('bossAtk');
  console.log(line, JSON.stringify(t));
}

const body = Object.entries(TUNING).map(([k, v]) => `  ${k}: { hp: ${v.hp.toFixed(3)}, atk: ${v.atk.toFixed(3)}, bossHp: ${v.bossHp.toFixed(3)}, bossAtk: ${v.bossAtk.toFixed(3)} },`).join('\n');
writeFileSync('src/data/tuning.ts', `export interface ChapterTuning { hp: number; atk: number; bossHp: number; bossAtk: number }

/** Per-chapter difficulty multipliers. Regenerated by \`npm run autotune\`. */
export const TUNING: Record<number, ChapterTuning> = {
${body}
};
`);
console.log('wrote src/data/tuning.ts');
