import { mkdirSync, writeFileSync } from 'node:fs';
import { Rng, hashStr } from '../core/rng';
import type { Policy } from '../core/bots';
import { memberStats, member, type GameState } from '../core/party';
import { CHAPTER_LEVEL, CHARS } from '../data/characters';
import { BOSSES } from '../data/enemies';
import { MECH_ORDER } from '../data/types';
import { SKILLS } from '../data/skills';
import { CHAPTERS } from '../story/chapters';
import { BOSS_BONUS, REG_BONUS, campaign, chapterState, fight, pickEncounter, pickParty, type FightRecord } from '../sim/simlib';
import { playthrough } from './playthrough';

const N = Number(process.argv[2] ?? 60);
const CAMP = Number(process.argv[3] ?? 6);
const out: string[] = [];
const log = (s = '') => { out.push(s); console.log(s); };
const pct = (x: number, d = 0) => `${(x * 100).toFixed(d)}%`;
const f1 = (x: number) => x.toFixed(1);
const mean = (a: number[]) => (a.length ? a.reduce((x, y) => x + y, 0) / a.length : 0);
const clamp01 = (x: number) => Math.max(0, Math.min(1, x));
const band = (x: number, lo: number, hi: number, soft: number) => clamp01(1 - Math.max(0, lo - x, x - hi) / soft);

function setLevelOffset(s: GameState, off: number) {
  for (const m of s.roster) { m.lvl = Math.max(1, m.lvl + off); const st = memberStats(m); m.hp = st.hp; m.mp = st.mp; }
}

interface Agg { win: number; hpLeft: number; rounds: number; close: number; low: number; n: number; mpFrac: number; items: number; ko: number }
function agg(rs: FightRecord[]): Agg {
  const wins = rs.filter((r) => r.win);
  return {
    n: rs.length, win: rs.filter((r) => r.win).length / rs.length, hpLeft: mean(rs.map((r) => r.hpLeft)), rounds: mean(rs.map((r) => r.rounds)),
    close: wins.length ? wins.filter((r) => r.minHp < 0.4).length / wins.length : 0, low: wins.length ? wins.filter((r) => r.low).length / wins.length : 0,
    mpFrac: mean(rs.map((r) => r.mpFrac)), items: mean(rs.map((r) => r.items)), ko: mean(rs.map((r) => r.ko)),
  };
}

function bossFight(ch: number, p: Policy, rng: Rng, off = 0, ids?: string[]): FightRecord {
  const s = chapterState(ch, ids, BOSS_BONUS);
  if (off) setLevelOffset(s, off);
  let last!: FightRecord;
  for (const g of BOSSES[ch]) last = fight(s, g, true, p, rng, 0.85, { noApply: true });
  return last;
}
function regFight(ch: number, p: Policy, rng: Rng, off = 0): FightRecord {
  const s = chapterState(ch, undefined, REG_BONUS);
  if (off) setLevelOffset(s, off);
  return fight(s, pickEncounter(ch, rng), false, p, rng, 0.5, { noApply: true });
}

log('# Balance and fun report');
log();
log(`Generated by \`npm run balance\` with ${N} samples per cell. Bots: smart (heuristic player), mash (attack only), random (uniform legal action).`);
log('All fights start from a party at the expected level for the chapter with the chapter\'s gear tier, full HP and MP, and standard supplies.');
log();

// ---------------------------------------------------------------- 1. policies
log('## 1. Win rates and fight length by policy');
log();
log('| Ch | Smart reg | Smart boss | Casual reg | Casual boss | Mash reg | Mash boss | Random reg | Random boss | Reg rounds | Boss rounds | Reg HP left | Boss HP left |');
log('|---|---|---|---|---|---|---|---|---|---|---|---|---|');
const rows: Record<number, { sReg: Agg; sBoss: Agg; mReg: Agg; mBoss: Agg; rReg: Agg; rBoss: Agg; cReg: Agg; cBoss: Agg }> = {};
const smartRecs: FightRecord[][] = [];
for (let ch = 1; ch <= 12; ch++) {
  const rng = new Rng(ch * 1009);
  const col: Record<string, FightRecord[]> = { sReg: [], sBoss: [], mReg: [], mBoss: [], rReg: [], rBoss: [], cReg: [], cBoss: [] };
  for (let i = 0; i < N; i++) {
    col.sReg.push(regFight(ch, 'smart', rng)); col.sBoss.push(bossFight(ch, 'smart', rng));
    col.mReg.push(regFight(ch, 'mash', rng)); col.mBoss.push(bossFight(ch, 'mash', rng));
    col.cReg.push(regFight(ch, 'casual', rng)); col.cBoss.push(bossFight(ch, 'casual', rng));
    if (i < N / 2) { col.rReg.push(regFight(ch, 'random', rng)); col.rBoss.push(bossFight(ch, 'random', rng)); }
  }
  rows[ch] = { sReg: agg(col.sReg), sBoss: agg(col.sBoss), mReg: agg(col.mReg), mBoss: agg(col.mBoss), rReg: agg(col.rReg), rBoss: agg(col.rBoss), cReg: agg(col.cReg), cBoss: agg(col.cBoss) };
  smartRecs.push([...col.sReg, ...col.sBoss]);
  const r = rows[ch];
  log(`| ${ch} | ${pct(r.sReg.win)} | ${pct(r.sBoss.win)} | ${pct(r.cReg.win)} | ${pct(r.cBoss.win)} | ${pct(r.mReg.win)} | ${pct(r.mBoss.win)} | ${pct(r.rReg.win)} | ${pct(r.rBoss.win)} | ${f1(r.sReg.rounds)} | ${f1(r.sBoss.rounds)} | ${pct(r.sReg.hpLeft)} | ${pct(r.sBoss.hpLeft)} |`);
}

// ---------------------------------------------------------------- 2. level sensitivity
log();
log('## 2. Level sensitivity');
log();
log('Smart bot win rate against the chapter boss when the whole party is offset from the expected level. A shallow slope means forgiving pacing. A cliff means grinding is required.');
log();
const offs = [-4, -2, -1, 0, 1, 2];
log(`| Ch | ${offs.map((o) => (o > 0 ? `+${o}` : `${o}`)).join(' | ')} |`);
log(`|---|${offs.map(() => '---').join('|')}|`);
const slopeByCh: number[] = [];
for (let ch = 1; ch <= 12; ch++) {
  const rng = new Rng(ch * 31 + 5);
  const cells = offs.map((o) => { let w = 0; const n = Math.max(20, Math.floor(N / 2)); for (let i = 0; i < n; i++) w += bossFight(ch, 'smart', rng, o).win ? 1 : 0; return w / n; });
  slopeByCh.push(cells[offs.indexOf(0)] - cells[0]);
  log(`| ${ch} | ${cells.map((c) => pct(c)).join(' | ')} |`);
}

// ---------------------------------------------------------------- 3. campaign
log();
log('## 3. Full campaign (smart bot, 11 random fights per chapter, shopping between chapters)');
log();
const camps = Array.from({ length: CAMP }, (_, i) => campaign('smart', 500 + i));
log('| Ch | Target level | Level at start | Regular win | Rests | Boss attempts | Gold earned |');
log('|---|---|---|---|---|---|---|');
const levelGap: number[] = [];
for (let ch = 0; ch < 12; ch++) {
  const lv = mean(camps.map((c) => c.levelsAtStart[ch]));
  const reg = mean(camps.map((c) => { const f = c.chapters[ch].fights.filter((x) => !x.boss); return f.filter((x) => x.win).length / f.length; }));
  const att = mean(camps.map((c) => c.chapters[ch].bossAttempts));
  const gold = mean(camps.map((c) => c.chapters[ch].goldGained));
  levelGap.push(lv - CHAPTER_LEVEL[ch + 1]);
  const rests = mean(camps.map((c) => c.chapters[ch].rests));
  log(`| ${ch + 1} | ${CHAPTER_LEVEL[ch + 1]} | ${f1(lv)} | ${pct(reg)} | ${f1(rests)} | ${f1(att)} | ${Math.round(gold)} |`);
}

// ---------------------------------------------------------------- 4. party viability
log();
log('## 4. Party composition viability');
log();
log('Boss win rate of the smart bot for sampled four-member parties that always include Wick. The tenth percentile shows how a poorly matched party fares. A small gap between it and the median means every partymate can carry a slot.');
log();
log('| Ch | Roster | Parties | Best | 10th percentile | Median | Mean | Worst | P10 / median |');
log('|---|---|---|---|---|---|---|---|---|');
const chapterMeans: number[] = [];
const viability: number[] = [];
for (let ch = 3; ch <= 12; ch++) {
  const rng = new Rng(ch * 71);
  const roster = CHARS.filter((c) => c.joinChapter <= ch).map((c) => c.id);
  const combos: string[][] = [];
  const COMBOS = 24;
  for (let i = 0; i < COMBOS; i++) {
    const pool = roster.filter((id) => id !== 'wick');
    const pick = ['wick'];
    while (pick.length < 4 && pool.length) pick.push(pool.splice(rng.int(pool.length), 1)[0]);
    combos.push(pick);
  }
  const n = Math.max(12, Math.floor(N / 4));
  const rates = combos.map((ids) => { let w = 0; for (let i = 0; i < n; i++) w += bossFight(ch, 'smart', rng, 0, ids).win ? 1 : 0; return w / n; }).sort((a, b) => a - b);
  const p10 = rates[Math.floor(rates.length * 0.1)], med = rates[Math.floor(rates.length / 2)];
  viability.push(med > 0 ? p10 / med : 0);
  chapterMeans.push(mean(rates));
  log(`| ${ch} | ${roster.length} | ${combos.length} | ${pct(rates[rates.length - 1])} | ${pct(p10)} | ${pct(med)} | ${pct(mean(rates))} | ${pct(rates[0])} | ${med > 0 ? (p10 / med).toFixed(2) : '-'} |`);
}

// ---------------------------------------------------------------- 5. character contribution
log();
log('## 5. Contribution per partymate');
log();
log('Each character is tested in boss fights at chapter 12 in a party of Wick, that character, and two random partymates. The table shows the character\'s share of party damage and healing and how the smart bot used the character\'s six skills.');
log();
log('| Character | Class | Fights | Damage share | Healing share | Skills used | Top skill share | Most used skill |');
log('|---|---|---|---|---|---|---|---|');
const covers: Record<string, number> = {};
let maxDominance = 0;
for (const c of CHARS) {
  const rng = new Rng(hashStr(c.id));
  const dmg: number[] = [], heal: number[] = [];
  const use: Record<string, number> = {};
  const fights = Math.max(16, Math.floor(N / 3));
  for (let i = 0; i < fights; i++) {
    const pool = CHARS.filter((x) => x.id !== 'wick' && x.id !== c.id).map((x) => x.id);
    const ids = ['wick', ...(c.id === 'wick' ? [] : [c.id])];
    while (ids.length < 4) ids.push(pool.splice(rng.int(pool.length), 1)[0]);
    const r = bossFight(12, 'smart', rng, 0, ids);
    const td = Object.values(r.dmgByChar).reduce((a, b) => a + b, 0) || 1;
    const th = Object.values(r.healByChar).reduce((a, b) => a + b, 0) || 1;
    dmg.push(r.dmgByChar[c.id] / td);
    heal.push(r.healByChar[c.id] / th);
    for (const [k, v] of Object.entries(r.actions)) if (c.learn.some(([, s]) => s === k)) use[k] = (use[k] ?? 0) + v;
  }
  const total = Object.values(use).reduce((a, b) => a + b, 0) || 1;
  const topSkill = Object.entries(use).sort((a, b) => b[1] - a[1])[0];
  const top = topSkill ? topSkill[1] / total : 0;
  const cover = c.learn.filter(([, s]) => (use[s] ?? 0) > 0).length / c.learn.length;
  covers[c.id] = cover;
  maxDominance = Math.max(maxDominance, top);
  log(`| ${c.name} | ${c.cls} | ${fights} | ${pct(mean(dmg))} | ${pct(mean(heal))} | ${Math.round(cover * 6)}/6 | ${pct(top)} | ${topSkill ? SKILLS[topSkill[0]].name : '-'} |`);
}

// ---------------------------------------------------------------- 6. mechanics
log();
log('## 6. New mechanic adoption');
log();
log('Average uses per boss fight of the mechanic introduced in each chapter, as used by the smart bot. A mechanic that is never used is decoration.');
log();
log('| Ch | Mechanic | Uses per boss fight | Fights using it |');
log('|---|---|---|---|');
const mechKey: Record<string, (r: FightRecord) => number> = {
  timeline: (r) => r.actions.guard ?? 0, weakness: (r) => r.openings, nerve: (r) => r.limits, stance: (r) => r.actions.stance ?? 0, rows: () => 0,
  reaction: (r) => r.reactions, field: () => 0, gasp: (r) => r.gasps + (r.actions.pact ?? 0), runes: () => 0, rewind: (r) => r.rewinds, ascend: (r) => r.ascends + r.rebirths, dusk: (r) => r.dusks,
};
const adoption: number[] = [];
for (let ch = 1; ch <= 12; ch++) {
  const rng = new Rng(ch * 17);
  const recs: FightRecord[] = [];
  for (let i = 0; i < Math.max(20, N / 2); i++) recs.push(bossFight(ch, 'smart', rng));
  const key = MECH_ORDER[ch - 1];
  const uses = recs.map(mechKey[key]);
  const frac = uses.filter((u) => u > 0).length / uses.length;
  adoption.push(['rows', 'field', 'runes'].includes(key) ? 1 : frac);
  log(`| ${ch} | ${key} | ${['rows', 'field', 'runes'].includes(key) ? 'n/a (passive)' : f1(mean(uses))} | ${['rows', 'field', 'runes'].includes(key) ? 'n/a' : pct(frac)} |`);
}

// ---------------------------------------------------------------- 7. story metrics
log();
log('## 7. Story structure');
log();
log('| Ch | Hero\'s journey stage | Story circle beats | Dialogue lines | Words | NPCs | Chests |');
log('|---|---|---|---|---|---|---|');
let totalWords = 0;
for (const c of CHAPTERS) {
  const lines: string[] = [];
  const walk = (cmds: unknown[]) => { for (const x of cmds) { if (typeof x === 'string') lines.push(x); else if (x && typeof x === 'object') { const o = x as Record<string, unknown>; if (Array.isArray(o.opts)) for (const op of o.opts as { do: unknown[] }[]) walk(op.do); if (Array.isArray(o.then)) walk(o.then); if (Array.isArray(o.else)) walk(o.else); } } };
  c.beats.forEach((b) => walk(b.script));
  const words = lines.reduce((a, l) => a + l.split(/\s+/).length, 0);
  totalWords += words;
  log(`| ${c.id} | ${c.stage} | ${c.beats.map((b) => b.circle).length}/8 | ${lines.length} | ${words} | ${c.npcs.length} | ${c.chests.length} |`);
}
log();
log(`Total scripted words: ${totalWords}.`);

// ---------------------------------------------------------------- 8. playthrough
log();
log('## 8. Scripted playthrough');
log();
const pt = await playthrough(77, 3, 0);
log(`The real story scripts run end to end with the smart bot (3 random fights per room). Reached ending: **${pt.ended}**. Dialogue lines shown: ${pt.lines}.`);
log();
log('| Ch | Level at start | Fights | Boss tries | Wipes |');
log('|---|---|---|---|---|');
for (const l of pt.logs) log(`| ${l.chapter} | ${f1(l.level)} | ${l.fights} | ${l.bossTries} | ${l.wipes} |`);

// ---------------------------------------------------------------- 9. fun proxies
log();
log('## 9. Fun proxies');
log();
log('These are heuristics, not measurements of enjoyment. Each sub-score is scaled from 0 to 1 against the target band shown.');
log();
const ALL = Array.from({ length: 12 }, (_, i) => rows[i + 1]);
const skillGap = mean(ALL.map((r) => r.sBoss.win - r.mBoss.win));
const randGap = mean(ALL.map((r) => r.sReg.win - r.rReg.win));
const bossTension = mean(ALL.map((r) => r.sBoss.close));
const regTension = mean(ALL.map((r) => r.sReg.close));
const regRounds = mean(ALL.map((r) => r.sReg.rounds));
const bossRounds = mean(ALL.map((r) => r.sBoss.rounds));
const cm = mean(chapterMeans);
const bossSpread = Math.sqrt(mean(chapterMeans.map((x) => Math.pow(x - cm, 2))));
const bossWinSmooth = 1 - Math.min(1, bossSpread / 0.2);
const comeback = mean(ALL.map((r) => r.sBoss.low));
const coverage = mean(Object.values(covers));
const partyViab = mean(viability);
const mechAdopt = mean(adoption);
const slopeScore = 1 - clamp01(mean(slopeByCh) / 0.9);
const levelTrack = 1 - clamp01(mean(levelGap.map((g) => Math.abs(g))) / 6);
const subs: [string, string, number, string][] = [
  ['Decision depth', `smart boss win minus mash boss win ${pct(skillGap)}; smart minus random on regular fights ${pct(randGap)}`, band(skillGap, 0.4, 1, 0.3) * 0.6 + band(randGap, 0.25, 1, 0.25) * 0.4, 'gap of at least 40 points'],
  ['Boss tension', `${pct(bossTension)} of boss wins dip below 40% party HP`, band(bossTension, 0.45, 0.85, 0.3), '45 to 85% of wins are close calls'],
  ['Regular fight ease', `${pct(regTension)} of regular wins are close calls`, band(regTension, 0.03, 0.22, 0.15), '3 to 22%'],
  ['Comeback drama', `${pct(comeback)} of boss wins pass below 30% party HP`, band(comeback, 0.3, 0.8, 0.3), '30 to 80%'],
  ['Fight pacing', `${f1(regRounds)} rounds per regular fight, ${f1(bossRounds)} per boss`, band(regRounds, 2.5, 4.5, 2) * 0.5 + band(bossRounds, 8, 14, 5) * 0.5, '2.5 to 4.5 and 8 to 14 rounds'],
  ['Difficulty smoothness', `mean boss win rate over sampled parties has a spread of ${pct(bossSpread)} between chapters`, bossWinSmooth, 'low spread between chapters'],
  ['Level forgiveness', `two levels below expected costs ${pct(mean(slopeByCh), 0)} of boss wins at four levels down`, slopeScore, 'shallow slope'],
  ['Level tracking', `campaign levels stay within ${f1(mean(levelGap.map((g) => Math.abs(g))))} of target on average`, levelTrack, 'within 2 levels'],
  ['Skill variety', `${pct(coverage)} of character skills used, top skill share at most ${pct(maxDominance)}`, clamp01(coverage / 0.8) * 0.6 + band(1 - maxDominance, 0.6, 1, 0.3) * 0.4, '80% coverage and no skill above 40% of use'],
  ['Party viability', `10th percentile party reaches ${f1(partyViab)} of the median on average`, band(partyViab, 0.75, 1, 0.45), '10th percentile above 75% of the median'],
  ['Mechanic adoption', `${pct(mechAdopt)} of new mechanics are used in boss fights`, band(mechAdopt, 0.6, 1, 0.4), 'at least 60%'],
  ['Story completeness', `${CHAPTERS.length} chapters, 8 beats each, ${totalWords} words`, clamp01(totalWords / 5000), '5000 or more words'],
];
log('| Metric | Observed | Target | Score |');
log('|---|---|---|---|');
for (const [name, obs, sc, tgt] of subs) log(`| ${name} | ${obs} | ${tgt} | ${pct(sc)} |`);
const weights = [1.5, 1.3, 0.8, 1, 1, 1, 1, 0.8, 1, 1, 1, 0.6];
const fun = subs.reduce((a, s, i) => a + s[2] * weights[i], 0) / weights.reduce((a, b) => a + b, 0);
log();
log(`**Composite proxy score: ${(fun * 100).toFixed(0)} / 100.**`);

mkdirSync('reports', { recursive: true });
writeFileSync('reports/balance-report.md', out.join('\n') + '\n');
console.log('\nWrote reports/balance-report.md');
void member; void pickParty; void SKILLS;
