import { writeFileSync } from 'node:fs';
import { Rng } from '../core/rng';
import { CHARS } from '../data/characters';
import { BOSSES } from '../data/enemies';
import { TRIM } from '../data/trim';
import { BOSS_BONUS, chapterState, fight, randomParty } from '../sim/simlib';

// Nudges each partymate's power so that every character adds about the same to a party's boss win rate.
// Each chapter is normalized by its own mean, because later chapters are harder and only late characters appear in them.
const ITERS = Number(process.argv[2] ?? 8);
const PARTIES = Number(process.argv[3] ?? 50);
const FIGHTS = Number(process.argv[4] ?? 6);
const CHAPTERS = [4, 6, 8, 10, 12];

for (const c of CHARS) TRIM[c.id] = 1;
for (let it = 0; it < ITERS; it++) {
  const delta: Record<string, number[]> = {};
  for (const ch of CHAPTERS) {
    const rng = new Rng(ch * 131 + it);
    const sum: Record<string, number> = {};
    const cnt: Record<string, number> = {};
    let total = 0;
    for (let p = 0; p < PARTIES; p++) {
      const ids = randomParty(ch, rng);
      let w = 0;
      for (let f = 0; f < FIGHTS; f++) {
        const s = chapterState(ch, ids, BOSS_BONUS);
        let last;
        for (const g of BOSSES[ch]) last = fight(s, g, true, 'smart', rng, 0.85, { noApply: true });
        w += last!.win ? 1 : 0;
      }
      total += w / FIGHTS;
      for (const id of ids) { sum[id] = (sum[id] ?? 0) + w / FIGHTS; cnt[id] = (cnt[id] ?? 0) + 1; }
    }
    const mean = total / PARTIES;
    for (const id of Object.keys(cnt)) (delta[id] ??= []).push(sum[id] / cnt[id] - mean);
  }
  const vals = CHARS.filter((c) => delta[c.id]).map((c) => ({ id: c.id, v: delta[c.id].reduce((a, b) => a + b, 0) / delta[c.id].length }));
  for (const x of vals) TRIM[x.id] = Math.min(1.2, Math.max(0.85, TRIM[x.id] * (1 - 0.3 * x.v)));
  console.log(`it ${it}: ` + vals.map((x) => `${x.id} ${x.v >= 0 ? '+' : ''}${(x.v * 100).toFixed(0)}/${TRIM[x.id].toFixed(2)}`).join('  '));
}
const body = CHARS.map((c) => `  ${c.id}: ${TRIM[c.id].toFixed(3)},`).join('\n');
writeFileSync('src/data/trim.ts', `/** Per-character power multipliers on HP, ATK, and MAG. Regenerated by \`npm run classtune\`. */\nexport const TRIM: Record<string, number> = {\n${body}\n};\n`);
console.log('wrote src/data/trim.ts');
