import type { ChapterDef } from './types';

export const CH1: ChapterDef = {
  id: 1, title: 'The Noon That Never Ends', stage: 'The Ordinary World', place: 'Tuck and the Belfry', seed: 101, mech: 'timeline',
  theme: { name: 'belfry', a: '#c8902e', b: '#ffe6a0', floor: 0, wall: 0, deco: ['gear', 'machine', 'candle', 'rock', 'mark'] },
  mechTitle: 'TURN TIMELINE',
  mechText: ['Every unit acts in order of speed.', 'The bar at the top shows who is next.', 'GUARD halves damage and comes back quickly.', 'Speed is life.'],
  partymate: 'pocket',
  intro: ['CHAPTER 1', 'THE NOON THAT', 'NEVER ENDS'],
  beats: [
    {
      circle: 'you', room: 1, note: 'Wick winds the Lamp for the forty thousandth time.',
      script: [
        { card: ['HOW TO PLAY', '', 'ARROWS OR WASD MOVE', 'Z TALKS AND CONFIRMS', 'X OPENS THE MENU', '', 'AN ARROW AT THE EDGE OF', 'THE SCREEN POINTS TO THE', 'NEXT STORY BEAT'] },
        'It has been noon for three hundred years.',
        'WICK|Thirty-eight. Thirty-nine. Forty. And the day holds, same as yesterday.',
        'WICK|Well, same as the one before it. There is no yesterday, is there.',
        'GROMMET|You are muttering at the crank again. You are nine turns behind.',
        'WICK|Sorry, Grommet. My mind wandered off.',
        'GROMMET|Then fetch it back and wind.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'The crank key snaps and Wick has to find a spare.',
      script: [
        'SNAP. The brass key breaks off in the Lamp socket and rolls under a bench.',
        'GROMMET|No. No, no, no. Wick, the noon is going to slip!',
        'WICK|And if it does?',
        'GROMMET|It never has. I am not about to find out on my shift.',
        'WICK|Gran used to say there was something after noon. Evening, she called it. Orange, she said, and everybody went quiet.',
        'GROMMET|Your gran said soup had feelings. Spare key is in the Belfry gearworks, up the stairs past the mite pens.',
        'WICK|Orange, though. Imagine.',
        'GROMMET|The KEY, Wick.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Wick crosses the Belfry door marked DO NOT ENTER (AFTER NOON) and meets Pocket.',
      script: [
        'The Belfry door is painted with a warning: DO NOT ENTER (AFTER NOON).',
        'WICK|After noon. Well, that is nobody, then.',
        'A vending machine blocks the hall. It hums, then clears its throat in a rattle of coins.',
        'POCKET|INSERT COIN. Or don\'t. Honestly, you are the first customer in three hundred years who looked at me twice.',
        'WICK|You can talk!',
        'POCKET|Dispensing is the job. The talking just sort of leaked in. What are you after?',
        'WICK|The spare Lamp key. And, I think, an evening.',
        'POCKET|Never stocked one. Could be worth a try.',
        { join: 'pocket' },
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Dust mites eat minutes in the gearworks and Wick finds a cog marked DUSK.',
      script: [
        'The gearworks tick in every direction at once. Dust mites crawl over the cogs, chewing the spare minutes.',
        'POCKET|Dust Mites. They eat anything that changes. Keeps the place tidy.',
        'WICK|Tidy is one word for it.',
        'Wick finds a brass cog on a shelf. It is engraved with one word: DUSK.',
        'WICK|Does this belong anywhere?',
        'POCKET|The Lamp dial. There is a notch for it. Nobody has turned the dial to that since the Archivist showed up.',
        'WICK|The who?',
        'POCKET|No idea. First thing I ever said that I wished I could take back out of the slot.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'The Lamp dial has a hidden notch and the Lamp whispers a plea.',
      script: [
        'At the top of the Belfry the Lamp hangs like a brass sun, wound tight and never moving.',
        'The dial beneath it reads DAWN, NOON, NOON, NOON. A fifth notch is worn smooth under a skin of polish.',
        'LAMP|...please...',
        'WICK|Was that the Lamp?',
        'POCKET|Don\'t look at me. I sell snacks.',
        'LAMP|...turn me... down...',
        'Pocket coughs up a coin and drops it in Wick\'s palm. It is stamped with a thin crescent.',
        'POCKET|Not one of mine. Where did that come from?',
        { give: 'dew', n: 2 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Dust Warden guards the dial and Wick fits in the DUSK cog.',
      script: [
        'A hulking machine unfolds from the ceiling, all hoses and polishing arms.',
        'WARDEN|STOP. NOTHING HAS CHANGED. NOTHING SHALL CHANGE. PLEASE REMAIN CLEAN.',
        'WICK|I only need to borrow a cog.',
        'WARDEN|BORROWING IS CHANGE.',
        { battle: 0 },
        'The Warden wheezes and folds itself into a small, mortified cube.',
        'WICK|Sorry about the dust.',
        'Wick presses the DUSK cog into the dial. For one second the Lamp dims to the color of a peach.',
        'POCKET|Wick. Look down.',
        'A dark shape lies across the floor beside Wick\'s boots. It moves when he moves.',
        { give: 'jar', n: 1 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Wick walks back through a village that has just seen its first shadow.',
      script: [
        'Wick and Pocket climb down the stairs. Every window in Tuck is full of faces.',
        'A dog barks at the ground. A little girl pokes a long dark shape that trails her feet.',
        'VILLAGER|IT FOLLOWS ME. IT COPIES ME. IT WON\'T STOP.',
        'WICK|That is a shadow. It just means you are standing somewhere.',
        'VILLAGER|Well, I did not ask to be standing somewhere.',
        'POCKET|Folks say that about most things I sell. They come around.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Grommet gives Wick a lantern and sends him to the Dead Letter Office.',
      script: [
        'GROMMET|You made a shadow.',
        'WICK|I did.',
        'GROMMET|Fifty years I wound that Lamp. Never once looked at the dial.',
        'WICK|Did you want to?',
        'GROMMET|Every day. Here. This was mine. It is a lantern, for when the Lamp is away.',
        { give: 'w1' },
        'GROMMET|The Lamp\'s post goes to the Dead Letter Office under the square. If it asked for anything, there will be a letter.',
        'WICK|Thank you, Grommet.',
        'GROMMET|Save it. Send me something orange.',
        { card: ['END OF CHAPTER 1', 'Wick\'s shadow stretches', 'across the village square.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'grommet', name: 'Grommet', room: 1, lines: { 0: ['Forty turns, every hour, rain or no rain. Not that we get rain.'], 2: ['Spare key is up in the gearworks. Hurry. I swear the noon is wobbling.'], 7: ['A shadow. Look at it, stretched out like a cat. I am proud. I also need to sit down.'] } },
    { id: 'baker', name: 'Baker', room: 1, lines: { 0: ['The loaves never get past pale. No afternoon to finish them in.'], 7: ['Now we bake by the shadow. Worse bread, honestly. But it is the first bread with a time on it.'] } },
    { id: 'mite', name: 'Mite Keeper', room: 3, lines: { 0: ['They eat minutes, so I feed them minutes. Mostly leftover ones. Got a bucket of Tuesdays out back.'] } },
    { id: 'sign', name: 'Sign', room: 4, lines: { 0: ['PLEASE DO NOT TOUCH THE LAMP DIAL. The words have been underlined many times, in many different hands.'] } },
    { id: 'wren', name: 'Night Wren', room: 8, lines: { 0: ['Evening song, take nine thousand. I know it by heart. I just have not heard anyone else sing it.'] } },
    { id: 'keeper', name: 'Storeroom Keeper', room: 9, lines: { 0: ['Lost property from three centuries of winders. Hats, key rings, one whole afternoon. Look all you like. The afternoon stays with me.'] } },
  ],
  chests: [{ room: 2, give: 'dew', n: 2 }, { room: 4, gold: 40 }, { room: 9, guard: ['gremlin', 'gremlin'], give: 'ink', n: 2 }],
};

export const CH2: ChapterDef = {
  id: 2, title: 'The Crescent Letter', stage: 'The Call to Adventure', place: 'The Dead Letter Office', seed: 202, mech: 'weakness',
  theme: { name: 'letters', a: '#b8a888', b: '#fff0c8', floor: 1, wall: 1, deco: ['books', 'machine', 'web', 'candle', 'flower'] },
  mechTitle: 'WEAKNESSES',
  mechText: ['Hit a foe with its weakness to deal more damage.', 'An OPENING makes your next turn arrive sooner.', 'Elements: EMBER FROST VOLT LUMEN UMBRA BLOOM.', 'Foes show weak marks once you see them hurt.'],
  partymate: 'thistle',
  intro: ['CHAPTER 2', 'THE CRESCENT LETTER'],
  beats: [
    {
      circle: 'you', room: 1, note: 'Wick enters a post office for mail nobody could deliver.',
      script: [
        'Under the square in Tuck there is an office with no sign and no lamp. Wick finds it by following a draft.',
        'WICK|Hello? I am looking for the Lamp\'s post.',
        'CLERK|Stamps are down the road. What we have here is regret, by the envelope.',
        'POCKET|I like her already.',
        'CLERK|Dead Letter Office. Everything in here was sent and nothing was received. Mostly the sender is noon.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'A letter waits addressed to the holder of a crescent coin.',
      script: [
        'A single pigeonhole glows faintly. The label reads: TO WHOEVER CARRIES THE CRESCENT.',
        'WICK|That is me. That is actually me.',
        'CLERK|Can\'t open it, though. Postmaster\'s knot. Only she can untie it.',
        'WICK|And where is she?',
        'CLERK|Sorting vault. Went in to file one letter about three hundred years ago.',
        'POCKET|I\'ll pack snacks. Obviously.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Wick drops down the undeliverable chute.',
      script: [
        'The only way into the sorting vault is a chute labeled RETURN TO SENDER.',
        'WICK|Is it safe?',
        'CLERK|Nobody has come back up it. Draw your own conclusions.',
        'POCKET|That did not help.',
        'WICK|Grab my sleeve.',
        { shake: 12 },
        'They fall through a mile of stamped paper and land in a heap of soft envelopes.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Paper monsters fill the vault and Wick follows a single moth.',
      script: [
        'The vault is a cathedral of pigeonholes. Paper bats wheel overhead, and somewhere an angry letter is yelling.',
        'A large grey moth hovers ahead, clutching a very old envelope.',
        'POCKET|She keeps flapping at us. I think that means follow.',
        'WICK|Excuse me! Are you the Postmaster?',
        'MOTH|Shh, I am mid-delivery. And yes.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Thistle opens the letter from the Lamp and joins Wick.',
      script: [
        'THISTLE|Thistle. Postmaster, Third Class. I have carried this one letter three hundred years because nobody would sign for it.',
        'WICK|I have the crescent coin.',
        'Thistle brushes her wing against the coin. The knot comes undone with a sigh.',
        'THISTLE|Read it aloud, dear. My eyes are a moth\'s, and a moth\'s eyes are mostly for lamps.',
        'WICK|"To whoever can hold this coin. I am the Lamp. I am tired. I was told to shine until the book closed, and the book has not closed."',
        'WICK|"Find the Tailor who stitched the Seams. Ask for Evening. Please. Yours, L."',
        'THISTLE|Well. Three hundred years of carrying it, and I never once guessed it was polite.',
        { join: 'thistle' },
        { give: 'ink', n: 2 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Undelivered, a golem of unread mail, must be read to be stopped.',
      script: [
        'The floor rumbles. Every unread letter in the vault lifts off its shelf and stitches itself into a towering shape.',
        'UNDELIVERED|I HAVE SO MUCH TO SAY AND NOBODY WILL READ IT.',
        'THISTLE|Oh, dear. The backlog.',
        'WICK|We will read every one. Let me just hit you a little first.',
        { battle: 0 },
        'The golem comes apart into a snowfall of paper. Each sheet lands face up.',
        'UNDELIVERED|...thank you...',
        { give: 'feather', n: 1 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Three hundred years of mail flies out over Tuck.',
      script: [
        'Thistle opens the vault hatch and the snowfall of letters pours into the sky.',
        'The letters find their houses. Doors open. People read on the doorstep.',
        'VILLAGER|It is from my husband. Three hundred years old. He says he is running a bit late.',
        'VILLAGER|Mine says I owe the baker eleven coins.',
        'THISTLE|Some letters are kind and some are accurate. Occasionally you get both.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Wick must decide whether to go find the Tailor.',
      script: [
        'WICK|The Lamp wants me to find a Tailor. I am a winder. I wind things. I have never found anyone.',
        'THISTLE|You could say no. I carried it this far. Nobody says you carry it the rest.',
        'WICK|I will think about it.',
        'POCKET|That is a no wearing a hat.',
        'WICK|It is a "let me sit somewhere soft first." Totally different.',
        { card: ['END OF CHAPTER 2', 'A crescent coin sits', 'in Wick\'s pocket.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'clerk', name: 'Clerk', room: 1, lines: { 0: ['Welcome to the Dead Letter Office. Everything here is right on time.'], 7: ['Half of these were replies to letters that landed a century later. Total mess. I have never been happier.'] } },
    { id: 'sorter', name: 'Sorter Moth', room: 4, lines: { 0: ['One letter at a time, that is my system. Do not ask how many are left.'], 4: ['The Postmaster found the coin holder? After all this time? Excuse me, I need to sit.'] } },
    { id: 'pigeon', name: 'Pigeon', room: 7, lines: { 0: ['Coo. I carry what nobody wants. Steady work, though. Nobody ever tells me to hurry.'] } },
    { id: 'sign', name: 'Sign', room: 3, lines: { 0: ['A stamp on the wall reads RETURN TO SENDER. The sender line is crossed out and NOON is written over it in a shaky hand.'] } },
    { id: 'stamper', name: 'Stamp Collector', room: 8, lines: { 0: ['I collect stamps off envelopes nobody opened. Best collection in the vault, and the saddest.'] } },
    { id: 'archivemoth', name: 'Archive Moth', room: 9, lines: { 0: ['Letters even the Lamp was afraid to send. We keep them in the dark. They seem calmer there.'] } },
  ],
  chests: [{ room: 3, give: 'ink', n: 2 }, { room: 5, gold: 60 }, { room: 9, guard: ['warden'], give: 'bomb1', n: 2 }],
};

export const CH3: ChapterDef = {
  id: 3, title: 'The Cupboard of No', stage: 'Refusal of the Call', place: 'Comfort Hollow', seed: 303, mech: 'nerve',
  theme: { name: 'hollow', a: '#e88ab0', b: '#ffd8e8', floor: 2, wall: 2, deco: ['tree', 'flower', 'rock', 'moon', 'pool'] },
  mechTitle: 'NERVE',
  mechText: ['Taking damage and acting fills each hero\'s NERVE gauge.', 'At full NERVE a hero can unleash a LIMIT skill.', 'Guarding also builds NERVE.', 'Limit skills cost nothing but can be used once a gauge fills.'],
  partymate: 'ajar',
  intro: ['CHAPTER 3', 'THE CUPBOARD OF NO'],
  beats: [
    {
      circle: 'you', room: 1, note: 'Wick hides in a soft forest made of pillows.',
      script: [
        'Wick has walked three days the wrong way. The road ends in a wood made entirely of pillows.',
        'WICK|I am not running away. I am resting. Those are different.',
        'POCKET|Did I say anything?',
        'THISTLE|Your whole body did, dear.',
        'A gentle voice drifts out of the trees: "Welcome, sweetheart. Stay as long as you like."',
      ],
    },
    {
      circle: 'need', room: 2, note: 'Mother Comfort offers Wick everything he wants except a way forward.',
      script: [
        'MOTHER|Come in, come in. Have a biscuit. Have ten. Nobody has ever left Comfort Hollow hungry, or awake.',
        'WICK|I only want a rest before the frightening part.',
        'MOTHER|Of course you do. Stay. The frightening part will keep till tomorrow.',
        'POCKET|There is no tomorrow. It has been noon for three hundred years.',
        'MOTHER|Shh. Biscuit.',
        'Wick eats a biscuit. It is very good. He does not leave.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Wick goes deeper into the hollow and builds a blanket fort.',
      script: [
        'Wick wanders deeper into the wood and pulls a thick quilt over his head.',
        'WICK|I will just stay in here a minute.',
        'THISTLE|Wick, this is a cupboard.',
        'WICK|It is a fort.',
        'POCKET|It is a cupboard with ambitions.',
        'From somewhere close by comes a slow, hollow knocking.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Wick finds a suit of armor that is also a door, hiding for the same reason.',
      script: [
        'In the next cupboard stands a suit of armor with a door in its chest. The door is open exactly one inch.',
        'AJAR|Oh. Please, do not come in. I am not, that is, I have never been ready.',
        'WICK|I am hiding too.',
        'AJAR|From what?',
        'WICK|An evening. Sort of.',
        'AJAR|From myself, I think. Something behind my door. It is very large and it is waiting, and I can hear it breathing.',
        'THISTLE|Does it sound dangerous?',
        'AJAR|It sounds sad. I find that worse.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'The pillows are frozen moments and Sir Ajar joins the party.',
      script: [
        'Wick slits a pillow open. Inside is one golden minute, perfectly kept: a child on a swing, mid-laugh.',
        'THISTLE|These are not pillows. They are moments. Someone has stuffed the whole wood with afternoons.',
        'AJAR|Nobody leaves. It feeds on wanting to stay.',
        'WICK|So Mother Comfort is not kind. She is a very soft wall.',
        'AJAR|If I open my door I must look inside. If I never do, I stay in this cupboard for good.',
        'WICK|Come with us. When you look, I will look too.',
        'AJAR|Sir Ajar. Knight, door, coward. Delighted.',
        { join: 'ajar' },
      ],
    },
    {
      circle: 'take', room: 6, note: 'Mother Comfort tries to keep them and they leave anyway.',
      script: [
        'The trees fold up. The quilts rise. Mother Comfort unfolds into a mountain of blankets with a kind face.',
        'MOTHER|Oh, my sweethearts. I cannot let you go. You will only get hurt.',
        'WICK|I know. I am scared. I am going anyway.',
        'MOTHER|Then I will have to hold you very tightly.',
        { battle: 0 },
        'Mother Comfort sags. Her blankets loosen. Across the wood, a thousand frozen minutes start to tick.',
        'MOTHER|They always leave in the end. I wish someone had told me that was allowed.',
        { give: 'salt', n: 2 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'The hollow wakes up with its first yawn.',
      script: [
        'On the way out the pillows begin to yawn. One by one the frozen afternoons turn into ordinary ones.',
        'A lamb wakes and trots off. A cat finishes a sneeze it began three centuries ago.',
        'AJAR|Everything is moving. Is that usual?',
        'THISTLE|Quite usual. You stop noticing after a week.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Wick decides to go find the Tailor after all.',
      script: [
        'At the edge of the wood Wick stops and looks back at all that softness.',
        'WICK|I thought if I turned the Lamp down I might wreck everything. The whole world. All of it.',
        'POCKET|You might.',
        'WICK|I might. But somebody asked nicely. I am going to find the Tailor.',
        'AJAR|Then I shall mind the door. Someone has to.',
        { card: ['END OF CHAPTER 3', 'The wood is quiet', 'behind them.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'lamb', name: 'Sleepy Lamb', room: 2, lines: { 0: ['Five more minutes. Five more. Five.'], 6: ['I woke up. Not sure about it yet. The grass is much louder than I remembered.'] } },
    { id: 'cat', name: 'Cat', room: 4, lines: { 0: ['I have been halfway through a sneeze since before you were born. Do not make me laugh.'], 6: ['ACHOO. Finally. Thank you, stranger. I feel ten pounds lighter.'] } },
    { id: 'owl', name: 'Night Owl', room: 5, lines: { 0: ['I am the only one here who thinks it is dark. Nobody believes me. I keep checking.'] } },
    { id: 'sign', name: 'Sign', room: 1, lines: { 0: ['A carved sign reads: COMFORT HOLLOW. POPULATION: EVERYONE WHO STAYED.'] } },
    { id: 'hedgehog', name: 'Pillow Hedgehog', room: 8, lines: { 0: ['Shh, I am a pillow. Please do not sit on me, I am full of opinions and most are about lying down.'] } },
    { id: 'quilter', name: 'Quilt Maker', room: 9, lines: { 0: ['I stitch spare minutes into quilts. It is slow work. Nobody has ever asked me to stop, which I try not to think about.'] } },
  ],
  chests: [{ room: 2, give: 'dew', n: 3 }, { room: 4, gold: 80 }, { room: 9, guard: ['undelivered'], give: 'feather', n: 2 }],
};

export const CH4: ChapterDef = {
  id: 4, title: 'Hoard & Vale, Chartered', stage: 'Meeting the Mentor', place: 'The Firm', seed: 404, mech: 'stance',
  theme: { name: 'firm', a: '#c84a3a', b: '#f0e0c0', floor: 3, wall: 3, deco: ['machine', 'books', 'pillar', 'statue', 'candle'] },
  mechTitle: 'STANCES',
  mechText: ['Each hero can shift between three stances.', 'STEADY: +25% DEF and RES.', 'FIERCE: +20% ATK and MAG, -15% DEF and RES.', 'SWIFT: +25% SPD. Shifting is free.'],
  partymate: 'ledger',
  intro: ['CHAPTER 4', 'HOARD & VALE, CHARTERED'],
  beats: [
    {
      circle: 'you', room: 1, note: 'A tower of filing cabinets stands where a dragon accountancy firm keeps its office.',
      script: [
        'Nobody has seen the Tailor in an age. The Tailor\'s accountant, though, has an address. It is the tallest filing cabinet in the world.',
        'POCKET|HOARD & VALE, CHARTERED ACCOUNTANTS. Says here, dragons only.',
        'AJAR|Why would we call on a firm of dragons?',
        'THISTLE|Because the Lamp\'s letter has a name scribbled in the margin. "Ask Ledger."',
        'An imp in a tiny tie blocks the door and smiles thinly.',
        'RECEPTION|Appointment? Dragon? Willing to be audited? Any one will do. I prefer the third.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'Ledger, a retired dragon, knows where the Tailor is but will not help for free.',
      script: [
        'Deep in the tower, in an office gone grey with dust, a tiny red dragon in spectacles hunches over an ancient desk.',
        'LEDGER|Go away. Retired. I am busy counting my retirement.',
        'WICK|We are looking for the Tailor. The Lamp sent us.',
        'LEDGER|The Lamp. Hm. Sit down, then. I owe the Lamp an apology, and it is a long one.',
        'LEDGER|I can show you where the Tailor went. First you sit the Firm\'s entrance exam. Nobody leaves here with an unaudited file.',
        'POCKET|Dragons and paperwork. What could go wrong.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Wick signs the visitor\'s book and the cost of entry goes unlisted.',
      script: [
        'The visitor\'s book is one ledger the size of a door. Every line wants a name, a purpose, and a cost.',
        'WICK|Name, Wick. Purpose, evening. Cost...',
        'LEDGER|Put "unknown." Best entry in the whole book.',
        { unlock: true },
        'The pages turn on their own. The floor opens onto a long drop of stacked files.',
      ],
    },
    {
      circle: 'search', room: 4, note: 'Ledger teaches Wick how to stand in a fight.',
      script: [
        'LEDGER|Back straight. No, not like that. Like you mean it.',
        'WICK|Is this fighting or posture?',
        'LEDGER|At my age, same lesson. There are three ways to stand. A fool knows one.',
        'LEDGER|Steady, when you need to outlast it. Fierce, when you need it over. Swift, when you need to be first. Change as you like. It costs nothing.',
        'AJAR|No teacher has ever called me steady before.',
        'LEDGER|You are steady. Also a door. Both are compliments.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Ledger reveals the Archivist and joins the party.',
      script: [
        'In the deepest vault lies a single folder stamped PAID IN FULL.',
        'LEDGER|Everything costs something. First law of the trade. The world got its bill a long time ago, and someone settled it in one payment so it would never come due.',
        'WICK|Who?',
        'LEDGER|Marrow Vale. First Lamplighter. Now she calls herself the Archivist. My oldest client and my worst mistake. I drew up the contract that froze the noon.',
        'THISTLE|You did this?',
        'LEDGER|I did the sums. She made the wish. Let me help you take it apart.',
        { join: 'ledger' },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Proctor grades the exam in a fight and Ledger gets a map.',
      script: [
        'A great white eye drops from the ceiling, clutching a red pen.',
        'PROCTOR|EXAM IN PROGRESS. PLEASE PUT AWAY ALL HOPES.',
        'LEDGER|Practice audit. Whatever you do, do not look at the pen.',
        { battle: 0 },
        'The Proctor makes one large check on its scoresheet and dissolves.',
        'PROCTOR|...PASSED. THIS HAS NEVER HAPPENED. I AM NOT SURE HOW TO FEEL.',
        { give: 'jar', n: 2 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Wick exits with the map and a badge that says AUDITED.',
      script: [
        'The lifts carry them up. The imp at the desk stamps each badge in turn: AUDITED.',
        'RECEPTION|Well done. First group in three hundred years to walk out alive and in the black.',
        'POCKET|We are excellent value.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Wick leaves with a map to the Transit Yard.',
      script: [
        'On the steps of the Firm Wick unfolds the map. The Seams are red thread. Off in the Margin sits a tiny empty square.',
        'WICK|I only ever wound things before.',
        'LEDGER|Now you keep accounts. Same thing, really. Only the crank is your attention.',
        'WICK|The map starts us at the Transit Yard.',
        { card: ['END OF CHAPTER 4', 'A red thread leads', 'off the edge of the map.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'reception', name: 'Receptionist', room: 1, lines: { 0: ['Dragons only. Or guests in excellent shoes. Lift a foot, please. Hm. Borderline.'], 7: ['Audited, were you? Good. Mind the gap on your way out. We had a client fall in during the nineties.'] } },
    { id: 'intern', name: 'Intern Imp', room: 3, lines: { 0: ['I have been filing this one page since before the noon began. It is a heavy page.'] } },
    { id: 'clerk', name: 'Vault Clerk', room: 5, lines: { 0: ['Leave anything stamped PAID alone. Those are the ones that go off.'], 4: ['Ledger is back? Oh no. Oh heavens. I will have to redo the whole third quarter.'] } },
    { id: 'sign', name: 'Sign', room: 2, lines: { 0: ['A memo reads: DEFERRED MOMENTS WILL BE COLLECTED AT THE END OF TIME. PLEASE HAVE EXACT CHANGE.'] } },
    { id: 'liftimp', name: 'Lift Imp', room: 8, lines: { 0: ['Lobby, down. Vault, down. Roof, down. No up button. Dragons never wanted one.'] } },
    { id: 'shredder', name: 'Shredder', room: 9, lines: { 0: ['I shred whatever has expired. Three hundred years and nothing has. I have never been so bored. Or so sharp.'] } },
  ],
  chests: [{ room: 2, give: 'ink', n: 2 }, { room: 4, gold: 120 }, { room: 9, guard: ['mothercomfort'], give: 'jar', n: 2 }],
};
