import type { ChapterDef } from './types';

export const CH1: ChapterDef = {
  id: 1, title: 'The Noon That Never Ends', stage: 'The Ordinary World', place: 'Tuck and the Belfry', seed: 101, mech: 'timeline',
  theme: { name: 'belfry', a: '#c8902e', b: '#ffe6a0', floor: 0, wall: 0, deco: ['gear', 'machine', 'candle', 'rock', 'mark'] },
  mechTitle: 'TURN TIMELINE',
  mechText: ['Every unit acts in order of speed.', 'The bar at the top shows who is next.', 'GUARD halves damage and comes back quickly.', 'Speed is life.'],
  partymate: 'pocket',
  intro: ['CHAPTER 1', 'THE NOON THAT', 'NEVER ENDS', '', 'The Ordinary World'],
  beats: [
    {
      circle: 'you', room: 1, note: 'Wick winds the Lamp for the forty thousandth time.',
      script: [
        { card: ['HOW TO PLAY', '', 'ARROWS OR WASD MOVE', 'Z TALKS AND CONFIRMS', 'X OPENS THE MENU', '', 'AN ARROW AT THE EDGE OF', 'THE SCREEN POINTS TO THE', 'NEXT STORY BEAT'] },
        'It has been noon for three hundred years.',
        'WICK|Forty turns of the crank, and the day holds. Forty turns, and the day holds.',
        'WICK|It always holds. It is a very reliable day.',
        'GROMMET|Stop narrating at the crank, Wick. You are nine turns behind.',
        'WICK|Sorry, Grommet. I was thinking.',
        'GROMMET|Thinking is how the noon slips. Wind.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'The crank key snaps. Wick wants something the world does not have: an evening.',
      script: [
        'SNAP. The brass key breaks off in the Lamp socket and rolls under a bench.',
        'GROMMET|Oh no. Oh no no no. The noon will slip. The noon will slip!',
        'WICK|What happens if the noon slips?',
        'GROMMET|Nobody knows. Nobody has ever let it.',
        'WICK|My gran used to say that after noon came something called "evening". She said it was orange and it made everyone quiet.',
        'GROMMET|Your gran also said soup had feelings. The spare key is in the Belfry gearworks. Go and get it.',
        'WICK|I want to see the evening, Grommet.',
        'GROMMET|Get the KEY, Wick.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Wick crosses the Belfry door marked DO NOT ENTER (AFTER NOON) and meets Pocket.',
      script: [
        'The Belfry door is painted with a warning: DO NOT ENTER (AFTER NOON).',
        'WICK|It is always noon. So that is just a door.',
        'A vending machine blocks the hall. It hums, then clears its throat with a rattle of coins.',
        'POCKET|INSERT COIN. Or do not. I have been waiting three hundred years for someone to ask me a question.',
        'WICK|You talk!',
        'POCKET|I dispense. Talking is a side effect. What do you want?',
        'WICK|The spare Lamp key, and maybe an evening.',
        'POCKET|I have never dispensed an evening. I would like to try.',
        { join: 'pocket' },
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Dust mites eat minutes in the gearworks. A cog marked DUSK fits nowhere.',
      script: [
        'The gearworks tick in every direction at once. Dust mites swarm the cogs and chew the spare minutes.',
        'POCKET|Those are Dust Mites. They keep the noon tidy by eating anything that changes.',
        'WICK|That is a terrible job.',
        'POCKET|They are very good at it.',
        'Wick finds a brass cog on a shelf. It is engraved with one word: DUSK.',
        'WICK|Where does this go?',
        'POCKET|Nowhere. It is a setting on the Lamp dial. The dial has a notch for it. Nobody has turned it since the Archivist came.',
        'WICK|Who is the Archivist?',
        'POCKET|I do not know. That is the first truth I have ever been sorry to sell.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'The Lamp dial has a hidden notch. The Lamp itself whispers a plea.',
      script: [
        'At the top of the Belfry the Lamp hangs like a brass sun, wound tight, never moving.',
        'The dial beneath it has four notches: DAWN, NOON, NOON, NOON. A fifth is worn smooth under a layer of polish.',
        'LAMP|...please...',
        'WICK|Did the Lamp just talk?',
        'POCKET|I dispense, I do not diagnose.',
        'LAMP|...turn me... down...',
        'Pocket drops a coin into Wick\'s hand. It is stamped with a thin crescent.',
        'POCKET|That is not a coin I had before. I think the Lamp sent it.',
        { give: 'dew', n: 2 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Dust Warden guards the dial. Wick takes the DUSK cog and cannot go back.',
      script: [
        'A hulking machine unfolds from the ceiling, all hoses and polishing arms.',
        'WARDEN|STOP. NOTHING HAS CHANGED. NOTHING SHALL CHANGE. PLEASE REMAIN CLEAN.',
        'WICK|I am just borrowing a cog.',
        'WARDEN|BORROWING IS CHANGE.',
        { battle: 0 },
        'The Warden wheezes and folds up into a very small, very embarrassed cube.',
        'WICK|Sorry about the dust.',
        'Wick fits the DUSK cog into the dial. For exactly one second the Lamp dims to the color of a peach.',
        'POCKET|Wick. You made a shadow. On purpose. There is no going back from that.',
        { give: 'jar', n: 1 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Wick walks back through a village that has just seen its first shadow.',
      script: [
        'Wick and Pocket climb down the stairs. Every window in Tuck is full of faces.',
        'A dog is barking at the ground. A child is poking a long dark shape that follows her feet.',
        'VILLAGER|IT FOLLOWS ME. IT COPIES ME. IT WON\'T STOP.',
        'WICK|It is called a shadow. It is how you know you are standing somewhere.',
        'VILLAGER|I do not like knowing that.',
        'POCKET|That is a normal first reaction. I have been selling it for years.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Grommet gives Wick the lantern. Wick leaves home with a question.',
      script: [
        'GROMMET|You made a shadow.',
        'WICK|I did.',
        'GROMMET|I wound the Lamp for fifty years and never once thought to look at the dial.',
        'WICK|Did you want to?',
        'GROMMET|Every single day. Take this. It was mine. It is a lantern for when the Lamp is away.',
        { give: 'w1' },
        'GROMMET|The Lamp\'s mail goes to the Dead Letter Office beneath the square. If it asked for something, there will be a letter.',
        'WICK|Thank you, Grommet.',
        'GROMMET|Do not thank me. Wind something for me when you find an evening.',
        { card: ['END OF CHAPTER 1', 'Wick learned that the day', 'has a dial.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'grommet', name: 'Grommet', room: 1, lines: { 0: ['Forty turns. No more, no less. That is the job.'], 2: ['The key is in the Belfry gearworks. Please hurry. I can feel the noon wobbling.'], 7: ['You made a shadow. I am very proud and I also need to sit down.'] } },
    { id: 'baker', name: 'Baker', room: 1, lines: { 0: ['It is noon. The bread is always slightly under-baked because it never gets later.'], 7: ['People are baking by the shadow now. The bread is getting WORSE. But it is better.'] } },
    { id: 'mite', name: 'Mite Keeper', room: 3, lines: { 0: ['Dust mites eat minutes. I keep them fed. It is a living.'] } },
    { id: 'sign', name: 'Sign', room: 4, lines: { 0: ['A sign reads: PLEASE DO NOT TOUCH THE LAMP DIAL. It has been underlined by several different hands.'] } },
    { id: 'wren', name: 'Night Wren', room: 8, lines: { 0: ['I keep practicing my evening song. There is no evening. I am getting very good at rehearsals.'] } },
    { id: 'keeper', name: 'Storeroom Keeper', room: 9, lines: { 0: ['This room holds what winders lose. Key rings, hats, and one whole afternoon. Feel free to look, but I am keeping the afternoon.'] } },
  ],
  chests: [{ room: 2, give: 'dew', n: 2 }, { room: 4, gold: 40 }, { room: 9, guard: ['gremlin', 'gremlin'], give: 'ink', n: 2 }],
};

export const CH2: ChapterDef = {
  id: 2, title: 'The Crescent Letter', stage: 'The Call to Adventure', place: 'The Dead Letter Office', seed: 202, mech: 'weakness',
  theme: { name: 'letters', a: '#b8a888', b: '#fff0c8', floor: 1, wall: 1, deco: ['books', 'machine', 'web', 'candle', 'flower'] },
  mechTitle: 'WEAKNESSES',
  mechText: ['Hit a foe with its weakness to deal more damage.', 'An OPENING makes your next turn arrive sooner.', 'Elements: EMBER FROST VOLT LUMEN UMBRA BLOOM.', 'Foes show weak marks once you see them hurt.'],
  partymate: 'thistle',
  intro: ['CHAPTER 2', 'THE CRESCENT LETTER', '', 'The Call to Adventure'],
  beats: [
    {
      circle: 'you', room: 1, note: 'Wick enters a post office for mail nobody could deliver.',
      script: [
        'Beneath the square in Tuck is an office with no sign and no light. Wick finds it by following a draft.',
        'WICK|Hello? I am looking for the Lamp\'s mail.',
        'CLERK|We do not sell stamps. We sell regret, in envelopes.',
        'POCKET|I like her already.',
        'CLERK|This is the Dead Letter Office. Everything here was sent. Nothing here was received. The sender is usually noon.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'A letter waits addressed to the holder of a crescent coin.',
      script: [
        'A single pigeonhole glows faintly. The label reads: TO WHOEVER CARRIES THE CRESCENT.',
        'WICK|That is me. That is literally me.',
        'CLERK|We cannot open it. It is sealed with a Postmaster\'s knot. Only the Postmaster can untie it.',
        'WICK|Where is the Postmaster?',
        'CLERK|In the sorting vault. She went in to sort one letter about three hundred years ago.',
        'POCKET|I will bring snacks.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Wick drops down the undeliverable chute.',
      script: [
        'The only way into the sorting vault is a chute labeled RETURN TO SENDER.',
        'WICK|Is it safe?',
        'CLERK|Nobody has ever returned from it, which is technically the point.',
        'POCKET|That is not a comfort.',
        'WICK|Hold on to me.',
        { shake: 12 },
        'They fall through a mile of stamped paper and land in a pile of soft envelopes.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Paper monsters fill the vault. Wick follows a single moth.',
      script: [
        'The vault is a cathedral of pigeonholes. The air is full of paper bats and angry letters.',
        'A large grey moth hovers ahead, carrying a very old envelope.',
        'POCKET|She is trying to get our attention. Politely. By flapping at us.',
        'WICK|Excuse me! Are you the Postmaster?',
        'MOTH|Shh. I am on a delivery. Also, yes.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Thistle opens the letter from the Lamp and joins Wick.',
      script: [
        'THISTLE|Thistle, Postmaster, Third Class. I have carried this one letter for three hundred years because nobody would take it.',
        'WICK|I have a crescent coin.',
        'Thistle touches her wing to the coin. The knot unties itself with a sigh.',
        'THISTLE|Read it out. My eyes are a moth\'s.',
        'WICK|"To whoever can hold this coin. I am the Lamp. I am tired. I was told to shine until the book closed, and the book has not closed."',
        'WICK|"Find the Tailor who stitched the Seams. Ask for Evening. Please. Yours, L."',
        'THISTLE|I have been waiting a very long time to be wrong about how this ends.',
        { join: 'thistle' },
        { give: 'ink', n: 2 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Undelivered, a golem of unread mail, must be read to be stopped.',
      script: [
        'The floor rumbles. Every unread letter in the vault rises and stitches itself into a towering shape.',
        'UNDELIVERED|I HAVE SO MANY THINGS TO SAY AND NOBODY WILL READ THEM.',
        'THISTLE|Oh, dear. It is the backlog.',
        'WICK|We will read them. All of them. Just let me hit you a little first.',
        { battle: 0 },
        'The golem comes apart into a snowfall of paper. Each sheet lands face up.',
        'UNDELIVERED|...thank you...',
        { give: 'feather', n: 1 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Three hundred years of mail flies out over Tuck.',
      script: [
        'Thistle opens the vault hatch and the snowfall of letters pours into the sky.',
        'The letters find their houses. Doors open. People read.',
        'VILLAGER|It is a love letter. From my husband. Three hundred years ago. He says he is running late.',
        'VILLAGER|Mine says I owe the bakery eleven coins.',
        'THISTLE|Some letters are kind. Some are accurate.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Wick has a mission and a choice he does not want.',
      script: [
        'WICK|The Lamp asked me to find the Tailor. I am a winder. I wind things.',
        'THISTLE|You can say no. I carried the letter this far. You do not have to carry it the rest.',
        'WICK|I am going to think about it.',
        'POCKET|That is a no with extra steps.',
        'WICK|That is a "let me go somewhere soft and think" with extra steps.',
        { card: ['END OF CHAPTER 2', 'The call has been', 'heard.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'clerk', name: 'Clerk', room: 1, lines: { 0: ['Welcome to the Dead Letter Office. Everything is on time.'], 7: ['Half of these letters were replies to letters that arrived a hundred years later. It is a mess and I love it.'] } },
    { id: 'sorter', name: 'Sorter Moth', room: 4, lines: { 0: ['I am sorting one letter at a time. It is a great system.'], 4: ['Wait, the Postmaster found the coin holder? I need to sit down.'] } },
    { id: 'pigeon', name: 'Pigeon', room: 7, lines: { 0: ['Coo. I deliver the mail nobody wants. It is steady work.'] } },
    { id: 'sign', name: 'Sign', room: 3, lines: { 0: ['A stamp on the wall reads: RETURN TO SENDER. The sender is crossed out. The word NOON is written over it.'] } },
    { id: 'stamper', name: 'Stamp Collector', room: 8, lines: { 0: ['I collect stamps from envelopes nobody read. My collection is enormous and completely unhappy.'] } },
    { id: 'archivemoth', name: 'Archive Moth', room: 9, lines: { 0: ['These are the letters not even the Lamp dared to send. They are kept in the dark, where they feel safer.'] } },
  ],
  chests: [{ room: 3, give: 'ink', n: 2 }, { room: 5, gold: 60 }, { room: 9, guard: ['warden'], give: 'bomb1', n: 2 }],
};

export const CH3: ChapterDef = {
  id: 3, title: 'The Cupboard of No', stage: 'Refusal of the Call', place: 'Comfort Hollow', seed: 303, mech: 'nerve',
  theme: { name: 'hollow', a: '#e88ab0', b: '#ffd8e8', floor: 2, wall: 2, deco: ['tree', 'flower', 'rock', 'moon', 'pool'] },
  mechTitle: 'NERVE',
  mechText: ['Taking damage and acting fills each hero\'s NERVE gauge.', 'At full NERVE a hero can unleash a LIMIT skill.', 'Guarding also builds NERVE.', 'Limit skills cost nothing but can be used once a gauge fills.'],
  partymate: 'ajar',
  intro: ['CHAPTER 3', 'THE CUPBOARD OF NO', '', 'Refusal of the Call'],
  beats: [
    {
      circle: 'you', room: 1, note: 'Wick hides in a soft forest made of pillows.',
      script: [
        'Wick has walked three days in the opposite direction. The road ended in a wood made entirely of pillows.',
        'WICK|I am not going. I am resting. There is a difference.',
        'POCKET|I have not said a word.',
        'THISTLE|You said it with your eyebrows.',
        'A gentle voice drifts out of the trees: "Welcome, dear. Stay as long as you like."',
      ],
    },
    {
      circle: 'need', room: 2, note: 'Mother Comfort offers everything Wick wants except the thing he needs.',
      script: [
        'MOTHER|Come in, come in. Have a biscuit. Have ten. Nobody has left Comfort Hollow hungry, or awake.',
        'WICK|I just want to rest before I do the scary thing.',
        'MOTHER|Of course you do. Stay. The scary thing will still be there tomorrow.',
        'POCKET|It has been noon for three hundred years. Tomorrow is a rumor.',
        'MOTHER|Shh. Biscuit.',
        'Wick eats a biscuit. It is very good. He does not leave.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Wick goes deeper into the hollow and builds a blanket fort.',
      script: [
        'Wick wanders deeper into the wood and pulls a thick quilt over his head.',
        'WICK|I am going to hide here for a while.',
        'THISTLE|Wick, this is a cupboard.',
        'WICK|It is a fort.',
        'POCKET|It is a cupboard with hopes.',
        'From somewhere close by comes a slow, hollow knocking.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Wick finds a suit of armor that is also a door, hiding for the same reason.',
      script: [
        'In the next cupboard stands a suit of armor with a door on its chest. The door is open exactly one inch.',
        'AJAR|Please do not come in. I am not ready. I have never been ready.',
        'WICK|I am hiding too.',
        'AJAR|From what?',
        'WICK|An evening.',
        'AJAR|I am hiding from what is inside me. There is something behind my door. I can feel it. It is very, very large, and it is waiting.',
        'THISTLE|Does it feel dangerous?',
        'AJAR|It feels sad. That is worse.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'The pillows are frozen moments. Sir Ajar joins.',
      script: [
        'Wick cuts a pillow open. Inside is a single golden minute, perfectly preserved: a child laughing on a swing.',
        'THISTLE|These are not pillows. They are moments. Someone has stuffed the wood with afternoons.',
        'AJAR|The hollow never lets anyone leave. It feeds on the wish to stay.',
        'WICK|Then Mother Comfort is not being kind. She is being a very nice wall.',
        'AJAR|If I open my door, I will have to look. If I do not, I will stay in this cupboard forever.',
        'WICK|Come with us. I will look when you look.',
        'AJAR|Sir Ajar. Knight, door, coward. Pleased to meet you.',
        { join: 'ajar' },
      ],
    },
    {
      circle: 'take', room: 6, note: 'Mother Comfort tries to keep them. They leave anyway.',
      script: [
        'The trees fold up. The quilts rise. Mother Comfort unfolds into a mountain of blankets with a kind face.',
        'MOTHER|Oh, sweethearts. I cannot let you go. You will only get hurt.',
        'WICK|I know. I am scared. I am going anyway.',
        'MOTHER|Then I will have to hold you very tightly.',
        { battle: 0 },
        'Mother Comfort sags. Her blankets loosen. Somewhere, a thousand frozen minutes start to tick.',
        'MOTHER|Nobody ever stays. They only ever leave. I wish someone had told me that was allowed.',
        { give: 'salt', n: 2 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'The hollow wakes up with its first yawn.',
      script: [
        'On the way out, the pillows begin to yawn. One by one, frozen afternoons turn into ordinary ones.',
        'A lamb wakes and trots away. A cat finishes a sneeze it began three centuries ago.',
        'AJAR|Everything is moving. Is that normal?',
        'THISTLE|It is quite normal. You get used to it.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Wick accepts the call.',
      script: [
        'At the forest edge, Wick stops and looks back at the soft wood.',
        'WICK|I was hiding because I was afraid the Lamp could not be turned down. I was afraid I would wreck the world.',
        'POCKET|You might.',
        'WICK|I might. But somebody asked nicely. I am going to find the Tailor.',
        'AJAR|I will guard the door. Somebody has to.',
        { card: ['END OF CHAPTER 3', 'Wick said yes.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'lamb', name: 'Sleepy Lamb', room: 2, lines: { 0: ['Five more minutes. Five more minutes. Five more.'], 6: ['I woke up. I am not sure I like it, but it is interesting.'] } },
    { id: 'cat', name: 'Cat', room: 4, lines: { 0: ['I have been mid sneeze since before you were born. It is a lot of pressure.'], 6: ['ACHOO. Finally. Thank you, stranger.'] } },
    { id: 'owl', name: 'Night Owl', room: 5, lines: { 0: ['I am the only creature here who thinks it is dark. Nobody believes me.'] } },
    { id: 'sign', name: 'Sign', room: 1, lines: { 0: ['A carved sign reads: COMFORT HOLLOW. POPULATION: EVERYONE WHO STAYED.'] } },
    { id: 'hedgehog', name: 'Pillow Hedgehog', room: 8, lines: { 0: ['I am a pillow. It is a defense mechanism. Please do not sit on me, I am full of opinions.'] } },
    { id: 'quilter', name: 'Quilt Maker', room: 9, lines: { 0: ['I stitch minutes into quilts. Nobody has asked me to stop, which is somehow worse.'] } },
  ],
  chests: [{ room: 2, give: 'dew', n: 3 }, { room: 4, gold: 80 }, { room: 9, guard: ['undelivered'], give: 'feather', n: 2 }],
};

export const CH4: ChapterDef = {
  id: 4, title: 'Hoard & Vale, Chartered', stage: 'Meeting the Mentor', place: 'The Firm', seed: 404, mech: 'stance',
  theme: { name: 'firm', a: '#c84a3a', b: '#f0e0c0', floor: 3, wall: 3, deco: ['machine', 'books', 'pillar', 'statue', 'candle'] },
  mechTitle: 'STANCES',
  mechText: ['Each hero can shift between three stances.', 'STEADY: +25% DEF and RES.', 'FIERCE: +20% ATK and MAG, -15% DEF and RES.', 'SWIFT: +25% SPD. Shifting is free.'],
  partymate: 'ledger',
  intro: ['CHAPTER 4', 'HOARD & VALE, CHARTERED', '', 'Meeting the Mentor'],
  beats: [
    {
      circle: 'you', room: 1, note: 'A tower of filing cabinets shaped like a dragon office.',
      script: [
        'The Tailor is a legend. The Tailor\'s accountant is an address. It is the tallest filing cabinet in the world.',
        'POCKET|HOARD & VALE, CHARTERED ACCOUNTANTS. Dragons only, apparently.',
        'AJAR|Why are we going to a firm of dragons?',
        'THISTLE|Because the Lamp\'s letter mentioned one name in the margin. "Ask Ledger."',
        'An imp in a tiny tie blocks the door and smiles thinly.',
        'RECEPTION|Do you have an appointment? Are you a dragon? Are you willing to be audited?',
      ],
    },
    {
      circle: 'need', room: 2, note: 'Ledger, a retired dragon, knows where the Tailor is but will not help for free.',
      script: [
        'Deep in the tower, in an office gone grey with dust, a tiny red dragon in spectacles hunches over an ancient desk.',
        'LEDGER|Go away. I am retired. I am counting my retirement.',
        'WICK|We are looking for the Tailor. The Lamp asked us.',
        'LEDGER|The Lamp. Oh. The Lamp. Sit. I owe the Lamp a very long, very specific apology.',
        'LEDGER|I can show you where the Tailor went. But first you must pass the Firm\'s entrance exam. Nobody leaves with a file unaudited.',
        'POCKET|It is dragons and paperwork. This is going to be fine.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Wick signs the visitor\'s book. The cost of entry is itemized.',
      script: [
        'The visitor\'s book is a single ledger the size of a door. Every line wants a name, a purpose, and a cost.',
        'WICK|Name: Wick. Purpose: evening. Cost: ...',
        'LEDGER|Write "unknown". It is the most honest entry in the book.',
        { unlock: true },
        'The pages turn on their own. The floor opens into a descent of stacked files.',
      ],
    },
    {
      circle: 'search', room: 4, note: 'Ledger teaches Wick how to stand in a fight.',
      script: [
        'LEDGER|Stand up straight. No, not like that. Like you mean it.',
        'WICK|Is this a fighting lesson or a posture lesson?',
        'LEDGER|At my age they are the same lesson. There are three ways to stand, and a fool only knows one.',
        'LEDGER|Steady, when you must endure. Fierce, when you must end it. Swift, when you must be first. Switch freely. The stance costs nothing.',
        'AJAR|This is the first time a teacher has called me steady.',
        'LEDGER|You are very steady. You are also a door. Both are compliments.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Ledger reveals the Archivist and joins the party.',
      script: [
        'In the deepest vault is a single folder, stamped PAID IN FULL.',
        'LEDGER|Every moment costs something. That is the first law of accounting. The world was billed a long time ago, and someone paid a single lump sum to stop the bill from coming due.',
        'WICK|Who?',
        'LEDGER|Marrow Vale. The First Lamplighter. She is now called the Archivist. She is my oldest client and my greatest mistake. I drew up the contract that froze the noon.',
        'THISTLE|Ledger. You did this?',
        'LEDGER|I did the math. She did the wish. Let me help you unpick it.',
        { join: 'ledger' },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Proctor grades the exam. The price of the map is a fair fight.',
      script: [
        'A great white eye unfolds from the ceiling, clutching a red pen.',
        'PROCTOR|EXAM IN PROGRESS. PLEASE PUT AWAY ALL HOPES.',
        'LEDGER|It is only a practice audit. Do not look directly at the pen.',
        { battle: 0 },
        'The Proctor marks a large check on a scoresheet and dissolves.',
        'PROCTOR|...PASSED. THIS IS AN UNUSUAL OUTCOME...',
        { give: 'jar', n: 2 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Wick exits with the map and a visitor badge that says AUDITED.',
      script: [
        'The lifts carry them up. The receptionist imp stamps each of their badges: AUDITED.',
        'RECEPTION|Congratulations. You are the first group in three hundred years to leave alive and in the black.',
        'POCKET|We are a good deal.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Wick carries accounts instead of only winding.',
      script: [
        'On the steps of the firm, Wick unfolds the map. The Seams are drawn as lines of red thread. The Margin is marked with a tiny, empty square.',
        'WICK|I used to just wind things.',
        'LEDGER|Now you keep accounts. Try it. It is the same, but the crank is your attention.',
        'WICK|The map says to start at the Transit Yard.',
        { card: ['END OF CHAPTER 4', 'The teacher has been', 'found.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'reception', name: 'Receptionist', room: 1, lines: { 0: ['Dragons only. Or guests with excellent footwear. Let me see your shoes.'], 7: ['You were audited, yes? Good. Please mind the gap at the exit.'] } },
    { id: 'intern', name: 'Intern Imp', room: 3, lines: { 0: ['I have been filing this one page since before the Noon. It is a lot of page.'] } },
    { id: 'clerk', name: 'Vault Clerk', room: 5, lines: { 0: ['Do not touch anything stamped PAID. Those are the ones that explode.'], 4: ['Ledger is back? Oh, heavens. I need to redo the whole Q3.'] } },
    { id: 'sign', name: 'Sign', room: 2, lines: { 0: ['A memo reads: DEFERRED MOMENTS WILL BE COLLECTED AT THE END OF TIME. PLEASE HAVE EXACT CHANGE.'] } },
    { id: 'liftimp', name: 'Lift Imp', room: 8, lines: { 0: ['Lift to the lobby is going down. Lift to the vault is going down. There is no up. It is a dragon thing.'] } },
    { id: 'shredder', name: 'Shredder', room: 9, lines: { 0: ['I shred what has expired. Nothing has expired in three hundred years. I am bored, and I am sharp.'] } },
  ],
  chests: [{ room: 2, give: 'ink', n: 2 }, { room: 4, gold: 120 }, { room: 9, guard: ['mothercomfort'], give: 'jar', n: 2 }],
};
