import type { ChapterDef } from './types';

export const CH5: ChapterDef = {
  id: 5, title: 'Mind the Gap', stage: 'Crossing the Threshold', place: 'The Transit Yard', seed: 505, mech: 'rows',
  theme: { name: 'yard', a: '#3ab0a0', b: '#e8f0a0', floor: 0, wall: 2, deco: ['gear', 'pillar', 'machine', 'web', 'flower'] },
  mechTitle: 'FRONT AND BACK ROWS',
  mechText: ['Heroes stand in the FRONT or BACK row.', 'Back row takes 40% less physical damage but deals 25% less.', 'Foes aim physical attacks at the front row more often.', 'Change rows in FORMATION from the menu.'],
  partymate: 'route9',
  intro: ['CHAPTER 5', 'MIND THE GAP'],
  beats: [
    {
      circle: 'you', room: 1, note: 'The edge of Tuck\'s swatch. A yard of dead buses.',
      script: [
        'The Tuck swatch ends at a stitched edge. Past the seam the map just stops and the sky starts.',
        'A yard of rusted buses sits in front of the seam. Every destination sign is dark.',
        'WICK|I have never been past the edge of the map.',
        'LEDGER|Nobody has. Only the Transit crosses a seam, and the Transit hasn\'t run since the Noon.',
        'POCKET|Funny. The vending machine by the gate told me the same thing. Then it kept my coin.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need a ticket that does not exist.',
      script: [
        'A ticket booth glows faintly. Inside, a spirit clerk in a peaked cap stares at nothing.',
        'CLERK|Seams? Sold out. Permanently. Try again yesterday.',
        'THISTLE|It\'s always noon, dear. Yesterday is today.',
        'CLERK|Then you\'re early. Well done.',
        'LEDGER|We don\'t want a ticket. We want a vehicle that runs on memory, and I\'m told one bus here still has a route that never ended.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Wick steps through the turnstile that only opens one way.',
      script: [
        'The turnstile to the yard spins once, slowly, and stops.',
        'TURNSTILE|THIS GATE ADMITS ONE DIRECTION ONLY. PLEASE CONFIRM YOU UNDERSTAND.',
        'WICK|Yes.',
        'AJAR|I don\'t, as it happens. Ought I to?',
        'TURNSTILE|NO. PLEASE PROCEED ANYWAY.',
        'They step through. The gate clicks shut behind them. Tuck shrinks to a patch of amber in a great dark.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Ghost commuters wait for a bus that stopped three hundred years ago.',
      script: [
        'Ghosts in neat coats line the platform. Each holds a ticket and checks a watch that doesn\'t move.',
        'COMMUTER|The 9 is late again. Mind you, I\'ve started to wonder whether it\'s coming at all.',
        'WICK|When did it stop?',
        'COMMUTER|Noon, right between two stops. Now and then I hear her horn out in the dark. Just the once, and then nothing.',
        'A low horn sounds far away. Everyone on the platform turns toward it.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Route 9 is found. She needs a fare in stories. She joins.',
      script: [
        'In the depot at the end of the line sits a big, ghostly bus with her headlights off.',
        'ROUTE 9|...passengers...?',
        'WICK|Yes. Very much passengers.',
        'ROUTE 9|Oh. I\'d forgotten that sound. The grumbling. Somebody knocking on the glass to ask where we are.',
        'POCKET|We\'re headed for the Seams. The far side.',
        'ROUTE 9|That\'s the last stop on my route. I never did find out what a bus does once she gets there.',
        'WICK|Neither do I. Come and see?',
        { join: 'route9' },
        { give: 'bomb2', n: 1 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Toll Gate asks for something true. They pay it.',
      script: [
        'A great toll gate hangs across the seam, a ticket machine welded to a portcullis.',
        'TOLL|TOLL REQUIRED. ONE TRUE THING PER PASSENGER. THIS IS A FIRST WARNING. THERE IS NO SECOND.',
        'WICK|I\'m scared the evening won\'t come, and that I\'ll be the one who asked for it.',
        'TOLL|ACCEPTED. NEXT.',
        'AJAR|There is a door inside me I will not open. I fear what stands behind it.',
        'TOLL|ACCEPTED.',
        'ROUTE 9|I\'m afraid nobody will ever climb aboard me again.',
        'TOLL|ACCEPTED. NOW THE BILL. PLEASE REMAIN ON THE PLATFORM.',
        { battle: 0 },
        'The gate rises, rattling. A long road of sewn stars opens into the dark beyond.',
      ],
    },
    {
      circle: 'return', room: 7, note: 'A test ride back, then forward across the first seam.',
      script: [
        'Route 9 fires up her engine for the first time in three centuries. Her headlights are pale moons.',
        'ROUTE 9|Hop on, loves. Mind the gap.',
        'The bus rolls over the seam and the world tilts. Behind them the Tuck swatch looks small.',
        'POCKET|Huh. I figured stars would be bigger.',
        'THISTLE|They\'re bigger than you think, Pocket. They\'re just far away.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'The party sees night for the first time.',
      script: [
        'Through the windscreen the Lamp hangs over a dark, star-stitched sky. From here it is a pale yellow dot.',
        'WICK|That looks like something somebody forgot to switch off.',
        'LEDGER|It looks small.',
        'WICK|Yeah.',
        { card: ['END OF CHAPTER 5', 'The Lamp, a yellow dot', 'in the rear window.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'ticket', name: 'Ticket Ghost', room: 2, lines: { 0: ['Tickets, please. Not that anyone\'s used one since the Noon. Habit.'], 5: ['Is that the Nine? Oh, my stars. Somebody go and tell my husband.'] } },
    { id: 'commuter', name: 'Commuter', room: 4, lines: { 0: ['I\'m not waiting. I\'m commuting, it\'s just slow. Platform four, the bench with the dent. Come by.'] } },
    { id: 'pigeon', name: 'Platform Pigeon', room: 1, lines: { 0: ['Coo. Came for the crumbs. Stayed because the ghosts talk to me. Nobody else here does.'] } },
    { id: 'sign', name: 'Sign', room: 5, lines: { 0: ['A timetable reads: ROUTE 9. LAST STOP: EVENING. FREQUENCY: EVERY THREE HUNDRED YEARS.'] } },
    { id: 'guard', name: 'Platform Guard', room: 8, lines: { 0: ['MIND THE GAP. I tell everyone that. Never once told the gap itself. Might be rude, that.'] } },
    { id: 'lostprop', name: 'Lost Property Clerk', room: 9, lines: { 0: ['Everything in here got left behind at noon. Mostly hats. There\'s a green one on the top shelf you could check. It\'s heavy.'] } },
  ],
  chests: [{ room: 3, give: 'bomb2', n: 1 }, { room: 5, gold: 160 }, { room: 9, guard: ['proctor'], give: 'ink2', n: 2 }],
};

export const CH6: ChapterDef = {
  id: 6, title: 'The Long Table', stage: 'Tests, Allies, Enemies', place: 'A Casino in the Sky', seed: 606, mech: 'reaction',
  theme: { name: 'table', a: '#2a9a5a', b: '#f0e060', floor: 2, wall: 3, deco: ['statue', 'pillar', 'candle', 'crystal', 'flower'] },
  mechTitle: 'ELEMENT REACTIONS',
  mechText: ['Hit a foe with an element and it is MARKED.', 'Hit a marked foe with a DIFFERENT element to trigger a REACTION.', 'Reactions add bonus damage and effects.', 'Ember+Frost is Steam. Lumen+Umbra is Eclipse.'],
  partymate: 'zug',
  intro: ['CHAPTER 6', 'THE LONG TABLE'],
  beats: [
    {
      circle: 'you', room: 1, note: 'The party lands on a floating casino shaped like a board.',
      script: [
        'The bus docks at a floating platform the size of a town. The whole thing is a black and white board lit by a thousand candles.',
        'ROUTE 9|End of the line for me, and I\'m not sure it counts. Nobody\'s waved.',
        'POCKET|A whole town that sells luck. I should be taking notes.',
        'LEDGER|It\'s called the Long Table. The House never loses because it never lets a game finish.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need a pass and allies to cross the table.',
      script: [
        'PAWN|One ticket per game. One game per guest. One guest per square.',
        'WICK|We\'re only passing through.',
        'PAWN|Everyone is only passing through. Nobody has got across in three hundred years.',
        'THISTLE|Somebody here must know the way. Somebody who still wants to win, or lose, or simply be done.',
        'AJAR|It is hard to find a friend where every other guest is an opponent.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'First game against a mob of pawns.',
      script: [
        'They sit at the first table. A mob of pawns shuffles into formation.',
        'PAWN|Your move.',
        'WICK|I don\'t know the rules.',
        'PAWN|Good. Then it\'s fair.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Games played to a draw forever. Dealers watch from the catwalk.',
      script: [
        'All over the Long Table, players sit across from each other with their pieces locked in a standoff.',
        'PLAYER|Checkmate is three moves off. It was three moves off when my beard was black.',
        'PLAYER|Don\'t get me wrong, I don\'t want to win. Winning would end it.',
        'WICK|That\'s awful.',
        'LEDGER|It\'s also very well run.',
        'At the far end, a lone witch made of chess pieces plays herself in the dark.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Zug joins. The smiling Stay appears and offers them a room.',
      script: [
        'ZUG|Stalemate. Again. That makes four hundred and six million, three hundred and twelve thousand. I keep a tally.',
        'WICK|Hi. We\'re trying to cross the Table.',
        'ZUG|You\'re moving pieces! Actually moving them! Sit, sit, I\'ll help. What else have I got on, besides losing to myself?',
        { join: 'zug' },
        'A warm voice, unhurried, drifts through the candlelight.',
        'STAY|Oh, what a lovely group. And so busy. Wouldn\'t you like to stay?',
        'WICK|Who are you?',
        'STAY|Stay. Vice President of Comfort, for the Archivist. All I ask is that you sit down. For good. It\'s so pleasant.',
        'ZUG|He works for the House. He\'s very nice about it. That\'s the worst part.',
        { battle: 0 },
        'Stay straightens his cuffs and steps back, still smiling, one shoe already fading.',
        'STAY|How rude. I\'ll keep a room for you anyway. Do drop in.',
      ],
    },
    {
      circle: 'take', room: 6, note: 'The House wants a bet: tomorrow. They play it out.',
      script: [
        'The last table is the House itself, a many-handed croupier with a single glowing eye.',
        'HOUSE|TO CROSS THE TABLE YOU MUST BET SOMETHING.',
        'WICK|Name it.',
        'HOUSE|TOMORROW.',
        'ZUG|Not tomorrow! We only have the one!',
        'WICK|I bet it. All of it. If I lose, I lose it. If I win, I finally get to have one.',
        'HOUSE|...NOBODY HAS EVER BET TO LOSE.',
        { battle: 1 },
        'The House slumps. The table clatters. A key-shaped chip slides across the felt.',
        { give: 'flask', n: 1 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'The crowd cheers a loss for the first time.',
      script: [
        'The crowd at the Long Table has gone silent. Then someone claps.',
        'PLAYER|We lost. We actually lost. Oh, it\'s over. It\'s lovely.',
        'PLAYER|I haven\'t finished a game in three hundred years. I forgot you get to stand up afterward.',
        'ZUG|I lost to you on purpose. Best move I ever made.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'The party is now a team. Zug sees a rival she wants to beat.',
      script: [
        'Night over the Table. The candles go out one at a time.',
        'ZUG|Stay will try again. He\'ll be nicer about it, and that\'s when he\'s dangerous.',
        'WICK|We\'ll be ready.',
        'ZUG|I hope so. I\'ve never had friends, you see. I\'m dreadful at it. I\'ll practice.',
        { card: ['END OF CHAPTER 6', 'A pawn left on the board,', 'and a key-shaped chip.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'gambler', name: 'Gambler', room: 2, lines: { 0: ['I\'m up three hundred years. Do you know how dull that gets? Nothing left to want.'], 7: ['I lost and I feel wonderful. Is this what everybody else was doing?'] } },
    { id: 'croupier', name: 'Croupier', room: 3, lines: { 0: ['Place your bets. That\'s all I\'ve got. The rest got lost in a storm, years back.'] } },
    { id: 'player', name: 'Patient Player', room: 4, lines: { 0: ['Shh. I\'m deciding. It\'ll be a few decades yet. The knight, I think, but then again the bishop.'] } },
    { id: 'sign', name: 'Sign', room: 6, lines: { 0: ['A sign reads: THE HOUSE ALWAYS WINS. Below it, in smaller letters: AT ABSOLUTELY NOTHING.'] } },
    { id: 'dealer', name: 'One-Card Dealer', room: 8, lines: { 0: ['I deal one card. It\'s always the last one in the deck. I never saw the first, and I\'d like to.'] } },
    { id: 'jackpot', name: 'Jackpot Door', room: 9, lines: { 0: ['I\'m the jackpot. Door, locked, very shiny. Funny, I used to know why I was proud of that.'] } },
  ],
  chests: [{ room: 3, give: 'ink2', n: 2 }, { room: 5, gold: 220 }, { room: 9, guard: ['tollgate'], give: 'bomb2', n: 2 }],
};

export const CH7: ChapterDef = {
  id: 7, title: 'The Foundry Star', stage: 'Approach to the Inmost Cave', place: 'The Foundry Star', seed: 707, mech: 'field',
  theme: { name: 'foundry', a: '#e8701e', b: '#ffd84a', floor: 2, wall: 0, deco: ['gear', 'rock', 'pillar', 'crystal', 'pool'] },
  mechTitle: 'BATTLEFIELDS',
  mechText: ['Some battles take place in a FIELD.', 'A field boosts one element and weakens another for everyone.', 'Check the field name in the corner.', 'Use it, or fight against it.'],
  partymate: 'kiln',
  intro: ['CHAPTER 7', 'THE FOUNDRY STAR'],
  beats: [
    {
      circle: 'you', room: 1, note: 'A fallen star whose core is a foundry.',
      script: [
        'A star has fallen into the sea of sky. Its crater glows red. From inside comes a slow, patient hammering.',
        'LEDGER|The door in the Margin can\'t be picked or broken. It wants a key that has been finished, and nothing in this world is finished.',
        'POCKET|I\'ve got a coupon for that.',
        'LEDGER|It isn\'t a joke, Pocket. It\'s a metallurgy problem.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need the key forged from the Lamp\'s cog.',
      script: [
        'WICK|The cog from the dial, the one marked DUSK. It\'s the right metal.',
        'LEDGER|It is. It can become the key, but somebody has to finish it. Finishing is a craft. These days it\'s nearly a crime.',
        'ROUTE 9|Who finishes things, then?',
        'THISTLE|A smith. Only one left, they say. He works inside the star and he hasn\'t put the hammer down once.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'They descend the crater in a bucket.',
      script: [
        'A bucket on a chain lowers them into the crater. The walls roar with heat.',
        'AJAR|I was forged for weather below the boiling point.',
        'POCKET|Nobody lean on me. There\'s ice cream in there.',
        { unlock: true },
        'The chain shivers. The air bends. Shapes move in the glow.',
      ],
    },
    {
      circle: 'search', room: 4, note: 'Forge corridors full of slag and bellows imps.',
      script: [
        'The tunnels are made of cooling slag. Bellows imps pump heat through the mountain.',
        'IMP|Keep the forge hot, that\'s the job. Don\'t ask us when it stops.',
        'WICK|Why is it still hot?',
        'IMP|Smith never stops, so we never stop. It\'s a steady living, honest.',
        'Ahead, a hammer rings on an anvil, regular as a pulse.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Kiln has been forging the same blade for three hundred years.',
      script: [
        'At the heart of the star stands an anvil the size of a house. A broad smith swings a hammer in his sleep.',
        'KILN|Nearly there. One more strike.',
        'WICK|How long have you been making that sword?',
        'KILN|Three hundred years. Nearly done.',
        'LEDGER|It isn\'t. It\'s a wish with an edge on it.',
        'KILN|Finish it and it\'s a thing. Things break. Long as I keep making it, it\'s only a dream, and dreams don\'t break.',
        'WICK|I\'ve got a cog that wants to be a key. It needs someone who can bear to be done.',
        'KILN|...Hm. I\'ve had a lot of practice at not being done.',
        { join: 'kiln' },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Furnace Saint guards the anvil. Kiln finishes the key.',
      script: [
        'The anvil gives a horrible groan. A seven-armed figure of black iron rises out of the fire.',
        'SAINT|THE FORGE IS HOLY. NOTHING LEAVES THE FORGE. NOTHING ENDS IN THE FORGE.',
        'KILN|My rule. Wrote it on the furnace door myself. Stand back, Wick. I\'ll argue with it.',
        { battle: 0 },
        'The Saint cools to a dull red and kneels. Kiln lifts his hammer and strikes once.',
        'A single clean note rings across the Star. The cog gleams. It is a key, and it is finished.',
        { give: 'flask', n: 1 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Stay watches from a cliff and offers a warning.',
      script: [
        'They climb the crater wall with the key warm in Wick\'s hand.',
        'A figure in cream sits on a lip of rock with a teacup.',
        'STAY|You finished something. How dreadful for you.',
        'WICK|You\'re the one with the room. The House\'s agent.',
        'STAY|I\'m the Archivist\'s friend, dear. She\'s so sad, and I keep her comfortable. You\'re going to make her finish. I can\'t bear to watch her cry.',
        'KILN|Not a threat, that. Worse. That was a sad man.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'The key is in Wick\'s hand. One thing is finished.',
      script: [
        'WICK|It\'s done. A finished thing. I haven\'t seen one in three hundred years.',
        'KILN|Feels good. Like a sneeze.',
        'LEDGER|We have the key. The door is in the Margin, at the edge of the last book, and we\'ll need a map of the Library to find it.',
        { card: ['END OF CHAPTER 7', 'A key, still warm.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'imp', name: 'Bellows Imp', room: 4, lines: { 0: ['Pump, pump, pump. Mind the left bellows, she\'s got a leak. Third one this week.'] } },
    { id: 'apprentice', name: 'Apprentice', room: 2, lines: { 0: ['Three hundred years I\'ve been the apprentice. He lets me sweep. Never lets me hit anything.'], 6: ['Kiln finished it! Does that mean I could finish something? Just a little thing?'] } },
    { id: 'slime', name: 'Friendly Slag', room: 3, lines: { 0: ['I\'m not hostile, I\'m just warm. People mix that up. Stand a bit back and we\'ll get on fine.'] } },
    { id: 'sign', name: 'Sign', room: 5, lines: { 0: ['A plaque reads: THIS ANVIL HAS NEVER BEEN IDLE. PLEASE KEEP IT THAT WAY. (SIGNED, THE ANVIL)'] } },
    { id: 'coal', name: 'Lump of Coal', room: 8, lines: { 0: ['Lump of coal. Opinions, mostly one: I\'d like to burn. Nobody ever asks what I\'d like.'] } },
    { id: 'anvilghost', name: 'First Anvil', room: 9, lines: { 0: ['I was the first anvil. Took every hammer there was. Only one ever said sorry afterward.'] } },
  ],
  chests: [{ room: 3, give: 'flask', n: 1 }, { room: 5, gold: 320 }, { room: 9, guard: ['stay'], give: 'ink2', n: 3 }],
};

export const CH8: ChapterDef = {
  id: 8, title: 'The Overdue Library', stage: 'The Ordeal', place: 'The Library of Unreturned Hours', seed: 808, mech: 'gasp',
  theme: { name: 'library', a: '#8a6ad8', b: '#e0d0ff', floor: 1, wall: 2, deco: ['books', 'web', 'candle', 'statue', 'moon'] },
  mechTitle: 'LAST GASP AND PACTS',
  mechText: ['A hero at 0 HP gets one LAST GASP turn at double damage, free of MP.', 'The PACT command spends 30% HP to boost the next attack by 80%.', 'You can only sign a Pact above 40% HP.', 'Fall bravely.'],
  partymate: 'ampere',
  intro: ['CHAPTER 8', 'THE OVERDUE LIBRARY'],
  beats: [
    {
      circle: 'you', room: 1, note: 'A library of every hour nobody returned.',
      script: [
        'The Library of Unreturned Hours is shelved right up to the moon. Every spine is a day somebody borrowed and forgot.',
        'LEDGER|Fines here are paid in time. It\'s how the Archivist keeps her books balanced.',
        'ZUG|Sounds expensive.',
        'KILN|Sounds fair. I\'d pay.',
        'A quiet voice rises from the catalog: "Shhh."',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need the book that describes the Archivist.',
      script: [
        'LEDGER|We want a biography of Marrow Vale. It should tell us how to open the door in the Margin.',
        'POCKET|Reference Desk, then. Always at the Reference Desk.',
        'DESK|It would be. But it\'s checked out. You\'ll have to fetch it from the Overdue Stacks, where we keep whatever hasn\'t come back.',
        'WICK|Who has it?',
        'DESK|The Overdue. A librarian, of sorts. It collects.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Each party member reads their own last page.',
      script: [
        'To enter the Overdue Stacks you read a single page. It is the last page of your own book.',
        'WICK|A small room. A lantern. I\'m old, and smiling. I think it\'s evening.',
        'AJAR|I see a door. It stands open. It is very quiet.',
        'POCKET|A coin slot. Empty. Somebody\'s hand is reaching for it. Wick, I think the hand is yours.',
        'THISTLE|An envelope. Delivered.',
        'ROUTE 9|An empty road, and a light at the end of it.',
        'They look at each other. Nobody speaks. It isn\'t as frightening as they expected. It\'s plainer than that.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Ampere waits in the storm stacks for a lightning strike that never came.',
      script: [
        'The Stacks crackle with static. On top of the tallest shelf a figure in a lightning-rod cap stares at the ceiling.',
        'AMPERE|Hush now. Any second. Any second!',
        'WICK|Any second what?',
        'AMPERE|The dawn bolt! Struck every morning, ninety years running. Then the Noon came and the sky just stopped. I\'ve been waiting up here since.',
        'THISTLE|Oh, you poor man.',
        'AMPERE|Poor? I\'ve never been happier. Mostly. I do miss it terribly.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'The Long Noon, a biography of Marrow Vale. Ampere joins.',
      script: [
        'On the highest shelf lies a slim volume: THE LONG NOON, by M. Vale.',
        'WICK|It isn\'t a biography. It\'s her diary.',
        'WICK|"My daughter Dawn was born at noon. She smiled for the first time. I asked the Lamp to hold the hour. It did. Then it would not let go."',
        'LEDGER|She froze the day because her daughter smiled in it. I wrote the contract for that wish.',
        'THISTLE|Oh, Marrow. That\'s no villain. That\'s a mother.',
        'AMPERE|I\'m coming with you! If there\'s a morning at the end of this, I want to be standing under it with my rod up.',
        { join: 'ampere' },
        { give: 'plume', n: 1 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Overdue comes to collect. The party pays with everything.',
      script: [
        'The shelves slam shut. A tall thin shape unfolds from the dark, with a clipboard and a great black ledger.',
        'OVERDUE|YOU HAVE BORROWED TWELVE HOURS, ONE NOON, AND A CONCEPT. THEY ARE DUE.',
        'WICK|We\'ll return them. We only need the book first.',
        'OVERDUE|THE FINE IS ONE LIFE. THAT IS THE STANDARD RATE.',
        'AJAR|Then we pay it the long way. Fight bravely. Fall bravely.',
        { battle: 0 },
        'The Overdue stamps its ledger with a sigh. PAID, PAID, PAID.',
        'OVERDUE|I HAVE NEVER SEEN A FINE PAID IN COURAGE. I DO NOT KNOW HOW TO FILE IT.',
        { give: 'flask', n: 2 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Lightning strikes at last.',
      script: [
        'The party leaves the Library with the diary. A rumble starts high in the sky.',
        'AMPERE|That isn\'t weather. That\'s a dawn trying to happen!',
        'A single bolt splits the ceiling. It strikes Ampere and he stands there, smoking and delighted.',
        'AMPERE|Ahhh. There you are. Oh, I\'ve missed you.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'They know the enemy grieves and is not evil.',
      script: [
        'The party rests in the shadow of the Library. Wick turns the diary over in his hands.',
        'WICK|I keep thinking we\'d know what to do if it were a monster.',
        'THISTLE|It\'s a mother holding on to a good day. That\'s much harder.',
        'LEDGER|Yes. Which is why it should be us who ask her to let go.',
        { card: ['END OF CHAPTER 8', 'A diary with a pressed', 'flower in it.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'desk', name: 'Reference Desk', room: 2, lines: { 0: ['Shhh. I can\'t answer questions, I can only point. And I\'ve mislaid my arm.'] } },
    { id: 'patron', name: 'Patron', room: 3, lines: { 0: ['Borrowed this to read on a Tuesday. It\'s still Tuesday. I\'m horribly behind.'] } },
    { id: 'worm', name: 'Bookworm', room: 5, lines: { 0: ['I\'m not eating the books. I\'m absorbing them. Big difference. Try the diary shelf, the paper tastes of tears.'] } },
    { id: 'sign', name: 'Sign', room: 4, lines: { 0: ['A sign reads: SILENCE IS PRICELESS. THE FINE FOR LOUDNESS IS HOURS.'] } },
    { id: 'quietone', name: 'The Quiet One', room: 8, lines: { 0: ['Shh. (The librarian would like it noted that this line is also a book.)'] } },
    { id: 'bookmark', name: 'Bookmark', room: 9, lines: { 0: ['I hold a page nobody reads. Best page in the library. I won\'t say which.'] } },
  ],
  chests: [{ room: 3, give: 'ink3', n: 1 }, { room: 5, gold: 400 }, { room: 9, guard: ['furnacesaint'], give: 'plume', n: 1 }],
};
