import type { ChapterDef } from './types';

export const CH5: ChapterDef = {
  id: 5, title: 'Mind the Gap', stage: 'Crossing the Threshold', place: 'The Transit Yard', seed: 505, mech: 'rows',
  theme: { name: 'yard', a: '#3ab0a0', b: '#e8f0a0', floor: 0, wall: 2, deco: ['gear', 'pillar', 'machine', 'web', 'flower'] },
  mechTitle: 'FRONT AND BACK ROWS',
  mechText: ['Heroes stand in the FRONT or BACK row.', 'Back row takes 40% less physical damage but deals 25% less.', 'Foes aim physical attacks at the front row more often.', 'Change rows in FORMATION from the menu.'],
  partymate: 'route9',
  intro: ['CHAPTER 5', 'MIND THE GAP', '', 'Crossing the Threshold'],
  beats: [
    {
      circle: 'you', room: 1, note: 'The edge of Tuck\'s swatch. A yard of dead buses.',
      script: [
        'The Tuck swatch ends at a stitched edge. Beyond the seam the map simply stops and the sky begins.',
        'A yard of rusted buses sits in front of the seam, each with an unlit sign.',
        'WICK|I have never been past the edge of the map.',
        'LEDGER|Nobody has. The Seams can only be crossed by the Transit. The Transit has not run since the Noon.',
        'POCKET|That is what the vending machine at the yard said too.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need a ticket that does not exist.',
      script: [
        'A ticket booth glows faintly. Inside, a spirit clerk in a peaked cap stares at nothing.',
        'CLERK|Tickets to the Seams? Sold out. Permanently. Come back yesterday.',
        'THISTLE|It is always noon. Yesterday is the same as today.',
        'CLERK|Then you are very early.',
        'LEDGER|We need a vehicle that runs on memory. There is one bus with a route that never ended.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Wick steps through the turnstile that only opens one way.',
      script: [
        'The turnstile to the yard spins once, slowly, and stops.',
        'TURNSTILE|THIS GATE ADMITS ONE DIRECTION ONLY. PLEASE CONFIRM YOU UNDERSTAND.',
        'WICK|I understand.',
        'AJAR|I do not. Is that a problem?',
        'TURNSTILE|IT IS FOR YOU. PLEASE PROCEED ANYWAY.',
        'They step through. The gate clicks shut. Behind them Tuck shrinks into a patch of amber in a great dark.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Ghost commuters wait for a bus that stopped three hundred years ago.',
      script: [
        'Ghosts in neat coats line the platform. Each holds a ticket and checks a watch that has not moved.',
        'COMMUTER|The 9 is late. It is always late. I am starting to think it is not coming.',
        'WICK|When did it stop?',
        'COMMUTER|At noon. On the dot. Right between stops. I can hear it, sometimes. A horn in the dark.',
        'A low horn sounds far away. Everyone on the platform turns toward it.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Route 9 is found. She needs a fare in stories. She joins.',
      script: [
        'In the depot at the end of the line sits a big, ghostly bus with her headlights off.',
        'ROUTE 9|...passengers...?',
        'WICK|We are passengers. We are very much passengers.',
        'ROUTE 9|I have not had a fare since the Noon. I miss them. I miss the complaining. I miss the knocking on the window to ask for the next stop.',
        'POCKET|We are going to the Seams. The far side.',
        'ROUTE 9|My route ends there. It is the last stop. I do not know what happens to a bus at the last stop.',
        'WICK|Neither do I. We can find out together.',
        { join: 'route9' },
        { give: 'bomb2', n: 1 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Toll Gate asks for something true. They pay it.',
      script: [
        'A great toll gate hangs across the seam, a ticket machine welded to a portcullis.',
        'TOLL|TOLL REQUIRED. ONE TRUE THING PER PASSENGER. THIS IS A FIRST WARNING. THERE IS NO SECOND.',
        'WICK|I am afraid the evening will not come and I will be the one who asked for it.',
        'TOLL|ACCEPTED. NEXT.',
        'AJAR|I am afraid of what is behind my door.',
        'TOLL|ACCEPTED.',
        'ROUTE 9|I am afraid I will never be used again.',
        'TOLL|ACCEPTED. NOW THE BILL. PLEASE REMAIN ON THE PLATFORM.',
        { battle: 0 },
        'The gate rises, rattling. A long road of sewn stars opens into the dark beyond.',
      ],
    },
    {
      circle: 'return', room: 7, note: 'A test ride back, then forward across the first seam.',
      script: [
        'Route 9 fires up her engine for the first time in three centuries. Her headlights are pale moons.',
        'ROUTE 9|Hop in. Mind the gap.',
        'The bus rolls over the seam and the world tilts. Behind them, for the first time, the Tuck swatch looks small.',
        'POCKET|I have never seen the stars. They are cheaper than I thought.',
        'THISTLE|They are not for sale.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'The party sees night for the first time.',
      script: [
        'Through the windscreen the Lamp, a pale yellow dot, hangs stuck over a dark and star-stitched sky.',
        'WICK|So that is what the Lamp looks like from outside.',
        'LEDGER|Lonely.',
        'WICK|Yes. I think so too.',
        { card: ['END OF CHAPTER 5', 'There is no going back.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'ticket', name: 'Ticket Ghost', room: 2, lines: { 0: ['Tickets, please. Not that you will need them.'], 5: ['Is that the Nine? Oh, my stars. Somebody tell my husband.'] } },
    { id: 'commuter', name: 'Commuter', room: 4, lines: { 0: ['I am not waiting. I am commuting. It is just very slow.'] } },
    { id: 'pigeon', name: 'Platform Pigeon', room: 1, lines: { 0: ['Coo. I came here for the crumbs and stayed for the company.'] } },
    { id: 'sign', name: 'Sign', room: 5, lines: { 0: ['A timetable reads: ROUTE 9. LAST STOP: EVENING. FREQUENCY: EVERY THREE HUNDRED YEARS.'] } },
    { id: 'guard', name: 'Platform Guard', room: 8, lines: { 0: ['MIND THE GAP. I say it to everyone. I have never said it to the gap. I hope it is not offended.'] } },
    { id: 'lostprop', name: 'Lost Property Clerk', room: 9, lines: { 0: ['Everything here was left behind at noon. Most of it is hats. One of them is crying.'] } },
  ],
  chests: [{ room: 3, give: 'bomb2', n: 1 }, { room: 5, gold: 160 }, { room: 9, guard: ['proctor'], give: 'ink2', n: 2 }],
};

export const CH6: ChapterDef = {
  id: 6, title: 'The Long Table', stage: 'Tests, Allies, Enemies', place: 'A Casino in the Sky', seed: 606, mech: 'reaction',
  theme: { name: 'table', a: '#2a9a5a', b: '#f0e060', floor: 2, wall: 3, deco: ['statue', 'pillar', 'candle', 'crystal', 'flower'] },
  mechTitle: 'ELEMENT REACTIONS',
  mechText: ['Hit a foe with an element and it is MARKED.', 'Hit a marked foe with a DIFFERENT element to trigger a REACTION.', 'Reactions add bonus damage and effects.', 'Ember+Frost is Steam. Lumen+Umbra is Eclipse.'],
  partymate: 'zug',
  intro: ['CHAPTER 6', 'THE LONG TABLE', '', 'Tests, Allies, Enemies'],
  beats: [
    {
      circle: 'you', room: 1, note: 'The party lands on a floating casino shaped like a board.',
      script: [
        'The Transit bus docks at a floating platform the size of a town. The whole thing is a black-and-white board, lit by a thousand candles.',
        'ROUTE 9|Last stop for the 9. First stop for the casino.',
        'POCKET|I have never been to a place that sells luck. My competitors?',
        'LEDGER|It is called the Long Table. The House never loses, because the House never lets a game end.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need a pass and allies to cross the table.',
      script: [
        'PAWN|One ticket per game. One game per guest. One guest per square.',
        'WICK|We are just crossing.',
        'PAWN|Everyone is just crossing. Nobody has crossed in three hundred years.',
        'THISTLE|Someone here must be able to show us the way. Someone who still wants to win, or lose, or finish.',
        'AJAR|Allies are hard to find in a place where everyone is an opponent.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'First game against a mob of pawns.',
      script: [
        'They sit at the first table. A mob of pawns shuffles into formation.',
        'PAWN|Your move.',
        'WICK|I do not know the rules.',
        'PAWN|That is how you know it is fair.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Games played to a draw forever. Dealers watch from the catwalk.',
      script: [
        'Everywhere at the Long Table, players sit across from each other with pieces in a permanent standoff.',
        'PLAYER|Checkmate is three moves away. It has been three moves away for three centuries.',
        'PLAYER|I do not want to win. Winning ends it.',
        'WICK|That is the most tragic thing I have ever heard.',
        'LEDGER|It is also, unfortunately, very well run.',
        'At the far end, a lone witch made of chess pieces plays herself in the dark.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Zug joins. The smiling Stay appears and offers them a room.',
      script: [
        'ZUG|Stalemate again. This makes four hundred and six million, three hundred and twelve thousand. I am counting.',
        'WICK|Hello. We are crossing the Table.',
        'ZUG|Ha. You are actually moving pieces. You are the first in my memory. Sit, sit. I will help you. I have nothing else to do except lose to myself.',
        { join: 'zug' },
        'A warm voice, unhurried, drifts through the candlelight.',
        'STAY|What a lovely group. I must say, you are very busy. Would you like to stay?',
        'WICK|Who are you?',
        'STAY|Stay. The Archivist\'s Vice President of Comfort. I just want you all to sit down. Forever. It is so pleasant.',
        'ZUG|He is the House\'s agent. He is very nice. He is also the worst.',
        { battle: 0 },
        'Stay straightens his cuffs and steps back, still smiling, one shoe already fading.',
        'STAY|How rude. I shall leave a room reserved for you. Do drop by.',
      ],
    },
    {
      circle: 'take', room: 6, note: 'The House wants a bet: tomorrow. They play it out.',
      script: [
        'The last table is the House itself, a many-handed croupier with a single glowing eye.',
        'HOUSE|TO CROSS THE TABLE YOU MUST BET SOMETHING.',
        'WICK|Name it.',
        'HOUSE|TOMORROW.',
        'ZUG|Do not bet tomorrow! We only have one!',
        'WICK|I bet it all. If I lose, I lose it. If I win, I get to have one.',
        'HOUSE|INTERESTING. NOBODY HAS EVER BET WITH THE INTENT OF LOSING THE BET.',
        { battle: 1 },
        'The House slumps. The table clatters. A key-shaped chip slides across the felt.',
        { give: 'flask', n: 1 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'The crowd cheers a loss for the first time.',
      script: [
        'The crowd at the Long Table has gone silent. Then someone claps.',
        'PLAYER|We lost. We finally lost. It is over. It is so wonderfully over.',
        'PLAYER|I have not finished a game in three hundred years. I forgot what it felt like.',
        'ZUG|I lost to you. On purpose. It was the best decision I have ever made.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'The party is now a team. Zug sees a rival she wants to beat.',
      script: [
        'Night over the Table. The candles are going out, one at a time, like a polite yawn.',
        'ZUG|Stay will try again. He will be nicer. That is what makes him dangerous.',
        'WICK|We will be ready.',
        'ZUG|I hope you are. I have never had friends. I am very bad at it. I shall improve.',
        { card: ['END OF CHAPTER 6', 'Allies found.', 'An enemy named.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'gambler', name: 'Gambler', room: 2, lines: { 0: ['I am up three hundred years. It has gotten very boring.'], 7: ['I lost and I feel amazing. Is this what people do?'] } },
    { id: 'croupier', name: 'Croupier', room: 3, lines: { 0: ['Place your bets. I have no other words. They were taken during a storm.'] } },
    { id: 'player', name: 'Patient Player', room: 4, lines: { 0: ['Do not distract me. I am thinking about my next move. It is going to take a while.'] } },
    { id: 'sign', name: 'Sign', room: 6, lines: { 0: ['A sign reads: THE HOUSE ALWAYS WINS. A smaller sign below reads: THE HOUSE ALWAYS WINS AT ABSOLUTELY NOTHING.'] } },
    { id: 'dealer', name: 'One-Card Dealer', room: 8, lines: { 0: ['I deal one card. It is always the last card. I have never seen the first one.'] } },
    { id: 'jackpot', name: 'Jackpot Door', room: 9, lines: { 0: ['I am the jackpot. I am a door. I am locked. I have forgotten why I am proud of this.'] } },
  ],
  chests: [{ room: 3, give: 'ink2', n: 2 }, { room: 5, gold: 220 }, { room: 9, guard: ['tollgate'], give: 'bomb2', n: 2 }],
};

export const CH7: ChapterDef = {
  id: 7, title: 'The Foundry Star', stage: 'Approach to the Inmost Cave', place: 'The Foundry Star', seed: 707, mech: 'field',
  theme: { name: 'foundry', a: '#e8701e', b: '#ffd84a', floor: 2, wall: 0, deco: ['gear', 'rock', 'pillar', 'crystal', 'pool'] },
  mechTitle: 'BATTLEFIELDS',
  mechText: ['Some battles take place in a FIELD.', 'A field boosts one element and weakens another for everyone.', 'Check the field name in the corner.', 'Use it, or fight against it.'],
  partymate: 'kiln',
  intro: ['CHAPTER 7', 'THE FOUNDRY STAR', '', 'Approach to the Inmost Cave'],
  beats: [
    {
      circle: 'you', room: 1, note: 'A fallen star whose core is a foundry.',
      script: [
        'A star has fallen into the sea of sky. Its crater glows red. From inside comes a slow, patient hammering.',
        'LEDGER|The Margin\'s door cannot be picked or broken. It needs a key that has been finished. Nothing in the world is finished.',
        'POCKET|I have a coupon for that.',
        'LEDGER|It is not a joke. It is a metallurgy problem.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need the key forged from the Lamp\'s cog.',
      script: [
        'WICK|The DUSK cog we took from the dial. It is the right metal.',
        'LEDGER|Correct. The cog will become a key. But someone must finish it. Finishing is an art. It is also a sin, in this era.',
        'ROUTE 9|Who finishes things?',
        'THISTLE|A smith. There is only one left. They say he works inside the star, and that he has never stopped.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'They descend the crater in a bucket.',
      script: [
        'A bucket on a chain drops them into the crater. The walls roar with heat.',
        'AJAR|I was built for temperatures under the boiling point.',
        'POCKET|I have ice cream in my belly. Nobody touch it.',
        { unlock: true },
        'The chain shivers. The air bends. Shapes move in the glow.',
      ],
    },
    {
      circle: 'search', room: 4, note: 'Forge corridors full of slag and bellows imps.',
      script: [
        'The tunnels are made of cooling slag. Bellows imps pump the heat through the mountain.',
        'IMP|We are keeping the forge hot. It is the only job. Do not ask when it ends.',
        'WICK|Why is the forge still hot?',
        'IMP|Because the smith never stops. And we never stop. It is a very stable economy.',
        'Ahead, a sound of hammer and anvil grows, regular as a pulse.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Kiln has been forging the same blade for three hundred years.',
      script: [
        'At the heart of the star stands an anvil the size of a house. A broad smith swings a hammer in his sleep.',
        'KILN|Nearly there. Just one more strike. Just one more.',
        'WICK|How long have you been making that sword?',
        'KILN|Three hundred years. It is nearly finished.',
        'LEDGER|It is not. It is a wish.',
        'KILN|If I finish it, it is a thing. A thing can break. As long as I keep making it, it is a dream, and dreams cannot break.',
        'WICK|I have a cog. It wants to be a key. It needs someone who is not afraid to be done.',
        'KILN|...I have a lot of practice in not being done.',
        { join: 'kiln' },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Furnace Saint guards the anvil. Kiln finishes the key.',
      script: [
        'The anvil gives a horrible groan. A seven-armed figure of black iron rises out of the fire.',
        'SAINT|THE FORGE IS HOLY. NOTHING LEAVES THE FORGE. NOTHING ENDS IN THE FORGE.',
        'KILN|That is my own rule. I wrote it on the furnace door. Wick, stand back. I will argue with it.',
        { battle: 0 },
        'The Saint cools to a dull red and kneels. Kiln lifts his hammer and strikes once.',
        'A single clean note rings across the Star. The DUSK cog gleams. It is a key, and it is finished.',
        { give: 'flask', n: 1 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Stay watches from a cliff and offers a warning.',
      script: [
        'They climb the crater wall with the key warm in Wick\'s hand.',
        'A figure in cream sits on a lip of rock with a teacup.',
        'STAY|You finished something. How awful for you.',
        'WICK|You are the House\'s agent. The one with the room.',
        'STAY|I am the Archivist\'s friend. She is very sad. So I keep her comfortable. You are going to make her finish. I cannot stand to see her cry.',
        'KILN|That was not a threat. That was worse. That was a sad man.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'The key is in Wick\'s hand. One thing is finished.',
      script: [
        'WICK|The first finished thing in three hundred years.',
        'KILN|It feels good. It feels like a sneeze.',
        'LEDGER|We have the key. The door is the Margin, at the edge of the last book. To reach it we will need a map of the Library.',
        { card: ['END OF CHAPTER 7', 'One thing is', 'finished.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'imp', name: 'Bellows Imp', room: 4, lines: { 0: ['Pump. Pump. Pump. I am very good at my job.'] } },
    { id: 'apprentice', name: 'Apprentice', room: 2, lines: { 0: ['I am the apprentice. I have apprenticed for three hundred years. No one has let me finish anything.'], 6: ['Kiln finished it! Does this mean I can finish something too?'] } },
    { id: 'slime', name: 'Friendly Slag', room: 3, lines: { 0: ['I am not hostile. I am warm. Some people get them confused.'] } },
    { id: 'sign', name: 'Sign', room: 5, lines: { 0: ['A plaque reads: THIS ANVIL HAS NEVER BEEN IDLE. PLEASE KEEP IT THAT WAY. (SIGNED, THE ANVIL)'] } },
    { id: 'coal', name: 'Lump of Coal', room: 8, lines: { 0: ['I am a lump of coal with opinions. The main one is that I want to burn. Nobody asks.'] } },
    { id: 'anvilghost', name: 'First Anvil', room: 9, lines: { 0: ['I was the first anvil. I have met every hammer. Only one of them felt sorry afterward.'] } },
  ],
  chests: [{ room: 3, give: 'flask', n: 1 }, { room: 5, gold: 320 }, { room: 9, guard: ['stay'], give: 'ink2', n: 3 }],
};

export const CH8: ChapterDef = {
  id: 8, title: 'The Overdue Library', stage: 'The Ordeal', place: 'The Library of Unreturned Hours', seed: 808, mech: 'gasp',
  theme: { name: 'library', a: '#8a6ad8', b: '#e0d0ff', floor: 1, wall: 2, deco: ['books', 'web', 'candle', 'statue', 'moon'] },
  mechTitle: 'LAST GASP AND PACTS',
  mechText: ['A hero at 0 HP gets one LAST GASP turn at double damage, free of MP.', 'The PACT command spends 30% HP to boost the next attack by 80%.', 'You can only sign a Pact above 40% HP.', 'Fall bravely.'],
  partymate: 'ampere',
  intro: ['CHAPTER 8', 'THE OVERDUE LIBRARY', '', 'The Ordeal'],
  beats: [
    {
      circle: 'you', room: 1, note: 'A library of every hour nobody returned.',
      script: [
        'The Library of Unreturned Hours is shelved to the moon. Every spine is a day someone borrowed and forgot.',
        'LEDGER|Overdue fines here are paid in time. The Library is how the Archivist balances the books.',
        'ZUG|That sounds expensive.',
        'KILN|That sounds like my kind of place. I want to be fined.',
        'A quiet voice rises from the catalog: "Shhh."',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need the book that describes the Archivist.',
      script: [
        'LEDGER|We need a biography of Marrow Vale. It will tell us how to open the door in the Margin.',
        'POCKET|The Reference Desk will have it. It is always at the Reference Desk.',
        'DESK|Yes. It is. But it is checked out. You must fetch it from the Overdue Stacks, where the books are kept by whoever has not returned them.',
        'WICK|Who has it?',
        'DESK|The Overdue. It is a librarian. It collects.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Each party member reads their own last page.',
      script: [
        'To enter the Overdue Stacks you must read a single page. It is the last page of your own book.',
        'WICK|I see... a small room. A lantern. I am older. I am smiling. I think it is evening.',
        'AJAR|I see a door. It is open. It is very quiet.',
        'POCKET|I see a coin slot. It is empty. A hand is reaching for it. I think the hand is yours, Wick.',
        'THISTLE|I see an envelope. Delivered.',
        'ROUTE 9|I see an empty road, and a light at the end of it.',
        'They look at each other. Nobody speaks. Everyone has just seen how they end. It is not as frightening as they expected. It is worse. It is ordinary.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Ampere waits in the storm stacks for a lightning strike that never came.',
      script: [
        'The Stacks crackle with static. In the top of the tallest shelf a figure in a lightning-rod cap stares at the ceiling.',
        'AMPERE|Hush. It is almost time. Any second now.',
        'WICK|What is?',
        'AMPERE|The dawn. The bolt. I get struck every morning. I have been struck every morning for ninety years, and then the Noon came, and I have been waiting ever since.',
        'THISTLE|That is the loneliest thing I have ever heard.',
        'AMPERE|It is a wonderful feeling. You should try it. I miss it more than anything.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'The Long Noon, a biography of Marrow Vale. Ampere joins.',
      script: [
        'On the highest shelf lies a slim volume: THE LONG NOON, by M. Vale.',
        'WICK|It is not a biography. It is her diary.',
        'WICK|"My daughter Dawn was born at noon. She smiled for the first time. I asked the Lamp to hold the hour. It did. Then it would not let go."',
        'LEDGER|Marrow froze the day because her daughter smiled in it. That is the wish I wrote the contract for.',
        'THISTLE|Oh, Marrow. That is not a villain. That is a mother.',
        'AMPERE|I am coming with you. If there is going to be a morning, I want to be at the end of the lightning rod.',
        { join: 'ampere' },
        { give: 'plume', n: 1 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Overdue comes to collect. The party pays with everything.',
      script: [
        'The shelves slam shut. A tall thin shape unfolds from the dark, with a clipboard and a great black ledger.',
        'OVERDUE|YOU HAVE BORROWED TWELVE HOURS, ONE NOON, AND A CONCEPT. THEY ARE DUE.',
        'WICK|We will return them. We just need the book.',
        'OVERDUE|THE FINE IS ONE LIFE. THAT IS THE STANDARD RATE.',
        'AJAR|Then we will pay it the long way. Fight bravely. Fall bravely.',
        { battle: 0 },
        'The Overdue stamps its ledger with a sigh. PAID, PAID, PAID.',
        'OVERDUE|I HAVE NEVER SEEN A FINE PAID IN COURAGE. I DO NOT KNOW HOW TO FILE IT.',
        { give: 'flask', n: 2 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Lightning strikes at last.',
      script: [
        'The party leaves the Library with the diary. A rumble starts high in the sky.',
        'AMPERE|That is not a storm. That is a dawn trying to happen.',
        'A single bolt splits the ceiling. It strikes Ampere and he stands there, smoking and delighted.',
        'AMPERE|Ahhh. There you are. I missed you.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'They know the enemy grieves and is not evil.',
      script: [
        'The party rests in the shadow of the Library.',
        'WICK|We are not fighting a monster. We are fighting a hug that will not let go.',
        'THISTLE|That is so much harder.',
        'LEDGER|Yes. It is. And that is why we are the right ones to do it.',
        { card: ['END OF CHAPTER 8', 'The enemy has a name.', 'The enemy has a reason.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'desk', name: 'Reference Desk', room: 2, lines: { 0: ['Shhh. I cannot answer questions. I can only point, and I have lost my arm.'] } },
    { id: 'patron', name: 'Patron', room: 3, lines: { 0: ['I borrowed this book to read on a Tuesday. It is still Tuesday. I am very behind.'] } },
    { id: 'worm', name: 'Bookworm', room: 5, lines: { 0: ['I am not eating the books. I am absorbing them. There is a difference.'] } },
    { id: 'sign', name: 'Sign', room: 4, lines: { 0: ['A sign reads: SILENCE IS PRICELESS. THE FINE FOR LOUDNESS IS HOURS.'] } },
    { id: 'quietone', name: 'The Quiet One', room: 8, lines: { 0: ['Shh. (The librarian has decided to mention that this is also a book.)'] } },
    { id: 'bookmark', name: 'Bookmark', room: 9, lines: { 0: ['I hold a page nobody reads. It is the most important page in the library. I will not tell you which.'] } },
  ],
  chests: [{ room: 3, give: 'ink3', n: 1 }, { room: 5, gold: 400 }, { room: 9, guard: ['furnacesaint'], give: 'plume', n: 1 }],
};
