import type { ChapterDef } from './types';

export const CH9: ChapterDef = {
  id: 9, title: 'The Null Garden', stage: 'Reward: Seizing the Sword', place: 'The Null Garden', seed: 909, mech: 'runes',
  theme: { name: 'garden', a: '#58b068', b: '#d8ff98', floor: 3, wall: 2, deco: ['tree', 'flower', 'statue', 'rock', 'pool'] },
  mechTitle: 'RUNES',
  mechText: ['Weapons and armor each have a rune socket.', 'Runes add effects like lifesteal, speed, or element power.', 'Equip them from the EQUIP menu. Runes are sold in shops.', 'Swap runes to suit the fight.'],
  partymate: 'fennel',
  intro: ['CHAPTER 9', 'THE NULL GARDEN', '', 'Reward: Seizing the Sword'],
  beats: [
    {
      circle: 'you', room: 1, note: 'A garden where nothing grows or dies.',
      script: [
        'The Null Garden is a hedge maze cut to precisely the same height in every direction.',
        'Every flower is open. Every petal is perfect. There is not a single bee.',
        'AJAR|It is lovely. Why do I feel nauseous?',
        'THISTLE|Because it is a painting of a garden that happens to be three-dimensional.',
        'KILN|I miss weeds.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'The Seed of Evening is hidden at the garden\'s heart.',
      script: [
        'LEDGER|The diary says the door to the Margin has two locks. The key we forged is one. The other is a seed.',
        'WICK|A seed?',
        'LEDGER|The Seed of Evening. Dusk cannot bloom unless it is planted. It is the only thing the Archivist feared enough to bury.',
        'ZUG|She buried it in a garden where nothing grows. It is an excellent hiding place. It is almost funny.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'They enter the hedge maze.',
      script: [
        'The hedge maze has no paths, only the exact absence of hedge.',
        'ROUTE 9|I can drive through anything, but this is too tidy. I am afraid to scratch it.',
        'POCKET|Left. Right. Left. I made up that route. I am enjoying being wrong.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'They find a gardener who prunes in secret.',
      script: [
        'Behind a hedge, a figure in a straw hat is sawing through a rosebush, very quietly.',
        'FENNEL|Shh. Do not tell the Archivist I am cutting. I am not supposed to cut. Nothing is supposed to change.',
        'WICK|Why are you cutting?',
        'FENNEL|Because a rose that never wilts never finishes being a rose. I keep trimming the edges of things, just to remind them they have edges.',
        'KILN|I like this one.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Fennel shows the one bud close to blooming. The Seed of Evening.',
      script: [
        'Fennel leads them to a clearing. In the center, a single bud the color of a sunset peeks from a pot.',
        'FENNEL|I have been tending this one for three hundred years. It wants to open. Every time it starts, the Garden presses it shut.',
        'WICK|That is the Seed of Evening.',
        'FENNEL|I know. I know what it means. If it blooms, the Garden ends. I have been both hoping and dreading it. I would like to be part of the end, if that is allowed.',
        'WICK|It is.',
        { join: 'fennel' },
        { give: 'r_ember', n: 1 },
        { give: 'r_siphon', n: 1 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Evergreen guards the bud. They prune it.',
      script: [
        'The garden stirs. A gigantic tree of perfectly straight trunks lumbers out of the hedge wall.',
        'EVERGREEN|I AM NEVER FINISHED. I AM NEVER DEAD. I AM THE GARDEN. DO NOT TOUCH THE BUD.',
        'FENNEL|I am sorry. I have to. You are very beautiful and you are in the way.',
        { battle: 0 },
        'The tree shudders. A single brown leaf drops from its crown, the first in three hundred years.',
        'The bud at the clearing trembles, swells, and opens. The Seed of Evening is a small, sleepy, orange star.',
        { give: 'starwater', n: 1 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Stay ambushes them on the way out.',
      script: [
        'The Garden begins to brown at the edges. Petals drift down like slow confetti.',
        'STAY|Oh, no. Oh, no no no. What have you done? It was so nice.',
        'STAY|Please. I am begging you. Put it back.',
        'WICK|I am sorry, Stay. It is not yours.',
        'STAY|Then I will have to ask more firmly.',
        { fight: ['stayecho', 'noonshade'] },
        'The echoes of Stay thin and fade. The real one is nowhere to be seen, but his teacup lies shattered in the grass.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'The bud blooms for the first time.',
      script: [
        'The Seed of Evening rests in Wick\'s palm, warm as a coal. The first dusk since the Noon leaks out of it, a thin orange glow at the edge of the sky.',
        'FENNEL|Oh. There it is. Oh, that is lovely. It is so much better than the painting.',
        'THISTLE|Wick. You are crying.',
        'WICK|I know. It is a good one.',
        { card: ['END OF CHAPTER 9', 'The reward is in hand.', 'The cost is coming.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'gnome', name: 'Garden Gnome', room: 2, lines: { 0: ['Do not pick anything. Do not water anything. Do not think about anything for too long.'], 7: ['A leaf fell! Somebody cover it!'] } },
    { id: 'bee', name: 'Lone Bee', room: 3, lines: { 0: ['Bzz. I am the last bee. I have nothing to do. Nothing ever needs pollinating.'] } },
    { id: 'scarecrow', name: 'Scarecrow', room: 5, lines: { 0: ['No crows come here. I have been told I am doing a good job. I am beginning to doubt it.'] } },
    { id: 'sign', name: 'Sign', room: 4, lines: { 0: ['A sign reads: PLEASE DO NOT WATER THE FLOWERS. THEY HAVE BEEN PERFECT SINCE BEFORE YOU WERE BORN.'] } },
    { id: 'snail', name: 'Garden Snail', room: 8, lines: { 0: ['I am very slow. In this garden I am the fastest thing that has ever changed.'] } },
    { id: 'seedsaver', name: 'Seed Saver', room: 9, lines: { 0: ['Every seed in here is saved for later. Later is a long time. I have started labeling them soon.'] } },
  ],
  chests: [{ room: 3, give: 'ink3', n: 1 }, { room: 5, gold: 500 }, { room: 9, guard: ['overdue'], give: 'r_bulwark', n: 1 }, { room: 9, give: 'r_quick', n: 1 }],
};

export const CH10: ChapterDef = {
  id: 10, title: 'The Unraveling', stage: 'The Road Back', place: 'The Seams', seed: 1010, mech: 'rewind',
  theme: { name: 'seams', a: '#ff7aa8', b: '#8ac8ff', floor: 1, wall: 1, deco: ['cog', 'web', 'crystal', 'rock', 'flower'] },
  mechTitle: 'REWIND',
  mechText: ['Once per battle you may REWIND.', 'Time folds back to the previous hero\'s turn and everything since is reshuffled.', 'Enemy attacks are re-rolled.', 'Use it after a bad turn.'],
  partymate: 'tick',
  intro: ['CHAPTER 10', 'THE UNRAVELING', '', 'The Road Back'],
  beats: [
    {
      circle: 'you', room: 1, note: 'The quilt is unpicking behind them.',
      script: [
        'The Garden frays. Threads peel from the hedges and float into the sky, a long pink ribbon of unwinding world.',
        'LEDGER|The Archivist knows. She is pulling the Seams to stop us. The road back is coming apart.',
        'ROUTE 9|Then we drive faster.',
        'A horn sounds from behind them: low, hollow, hungry.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need someone who can move through time itself.',
      script: [
        'FENNEL|Those are the Hounds of Hours. They chase anything that moves out of step.',
        'ZUG|We are out of step by definition. What do we do?',
        'THISTLE|We need to move between the ticks. There is a rabbit who does that. Everyone on the Seams knows him. He is always early.',
        'WICK|Always early?',
        'THISTLE|And never on time. It is complicated.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'They sprint onto the thread road.',
      script: [
        'The road is one long red thread, pulled taut over nothing.',
        'POCKET|I would like to go on record as saying I do not like this.',
        'WICK|Noted. Run.',
        { unlock: true },
        'Behind them, the ground unpicks itself with a sound like a long ripping sigh.',
      ],
    },
    {
      circle: 'search', room: 4, note: 'They find a clock with a missing minute hand.',
      script: [
        'In the middle of the road stands a grandfather clock with no hands. A rabbit made of clockwork paces around it, wringing his paws.',
        'TICK|I am early! I am late! I am both! Where is my minute hand?',
        'WICK|Hello. Are you Tick?',
        'TICK|I was here yesterday, which is today, which is three hundred years ago. I have been stuck at eleven fifty nine for all of them.',
        'TICK|My minute hand was stolen by the Hound. Get it back and I will show you how to fold time.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'They find the stolen minute hand. Tick joins.',
      script: [
        'They find the minute hand in a bird\'s nest of threads, still ticking, still gently annoyed.',
        'TICK|Oh! Oh, thank you! I can feel the seconds again! There they are. Hello, seconds.',
        'TICK|Let me show you. If you ever make a bad move, you can take one moment back. Just one. But only if the people in it are willing.',
        'WICK|Are they?',
        'TICK|They are friends. Friends are always willing.',
        { join: 'tick' },
        { give: 'feather', n: 2 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Hound of Hours is fought and turned aside.',
      script: [
        'The horn is very close now. A hound of silver minute-hands and clock-faces lopes out of the fray.',
        'HOUND|LATE. LATE. YOU ARE LATE. EVERYONE IS ALWAYS LATE.',
        'TICK|I am not. I am early, and I have a good excuse.',
        { battle: 0 },
        'The Hound whines and its clock-faces go soft. It curls up in a heap of ticking silver.',
        'WICK|Good dog. Good, tired dog.',
        { give: 'flask', n: 2 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'They reach the Margin door at the edge of the world.',
      script: [
        'At the end of the thread road stands a door with no wall. It is taller than a cathedral and shaped like an empty page.',
        'LEDGER|That is the door to the Margin.',
        'ZUG|I thought there would be more drama.',
        'Somewhere beyond the door, something very old sighs.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Tick\'s clock finally moves to twelve.',
      script: [
        'Tick\'s chest gives a small click. The clockwork hand lifts from eleven fifty nine.',
        'TICK|It is moving. It is twelve. It is noon. It is really noon. It is ticking.',
        'WICK|It has always been noon.',
        'TICK|Not like this. This one is moving.',
        { card: ['END OF CHAPTER 10', 'The road back', 'ends at a door.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'spool', name: 'Spool', room: 2, lines: { 0: ['I am a spool. I have been holding this thread since the sewing. I am very tired.'] } },
    { id: 'button', name: 'Loose Button', room: 3, lines: { 0: ['I fell off a coat three hundred years ago. I have been waiting for someone to sew me back.'], 6: ['Hey, can one of you sew? Hello?'] } },
    { id: 'snip', name: 'Old Needle', room: 5, lines: { 0: ['I am sharp, and I am worried. I have not pricked anyone in decades.'] } },
    { id: 'sign', name: 'Sign', room: 4, lines: { 0: ['A sign reads: PLEASE KEEP FEET OFF THE THREAD. IT IS THE ONLY THING HOLDING THE WORLD TOGETHER.'] } },
    { id: 'thimble', name: 'Thimble', room: 8, lines: { 0: ['I am a thimble. I am worn by a giant who left. I keep guarding the finger.'] } },
    { id: 'patch', name: 'Patch', room: 9, lines: { 0: ['Patches have feelings. Mine is: please, please stop unraveling. Also: is that a needle?'] } },
  ],
  chests: [{ room: 3, give: 'ink3', n: 1 }, { room: 5, gold: 600 }, { room: 9, guard: ['evergreen'], give: 'r_edge', n: 1 }],
};

export const CH11: ChapterDef = {
  id: 11, title: 'The Last Page', stage: 'Resurrection', place: 'The Margin', seed: 1111, mech: 'ascend',
  theme: { name: 'margin', a: '#a0a0b8', b: '#ffffff', floor: 3, wall: 3, deco: ['moon', 'pillar', 'crystal', 'statue', 'rock'] },
  mechTitle: 'ASCENSION AND REBIRTH',
  mechText: ['At full NERVE you may ASCEND instead of using LIMIT.', 'Ascended heroes gain 30% ATK, MAG, SPD and cast free for four turns.', 'In boss fights, a wiped party is REBORN once at half HP with full NERVE.', 'Dying is only a setback.'],
  partymate: 'ash',
  intro: ['CHAPTER 11', 'THE LAST PAGE', '', 'Resurrection'],
  beats: [
    {
      circle: 'you', room: 1, note: 'The party steps into blank white.',
      script: [
        'Beyond the door there is no floor. There is only white, with a faint grid of writing lines.',
        'AMPERE|It is a page. We are standing on a page.',
        'POCKET|It is a very large, very empty page.',
        'FENNEL|That is where the Archivist keeps what has not been written yet.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They must confront Marrow Vale.',
      script: [
        'LEDGER|We have the key. We have the seed. All that remains is Marrow.',
        'THISTLE|She is not going to want to hear it.',
        'LEDGER|No. But she is going to have to. I wrote the contract. I will be the one to read her the terms.',
        'Somewhere ahead, a pen scratches. It does not stop.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'They step onto the page.',
      script: [
        'They walk across the white. Where they step, black letters appear: ROUTE 9 WALKED. KILN WALKED. TICK WALKED.',
        'TICK|I am being narrated. I do not like being narrated.',
        'WICK|Stay together. Do not read too far ahead.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Redactions and erasures stand between them and the author.',
      script: [
        'Black bars and pale angels patrol the margins. They look at each of the party in turn. They try to smudge them out.',
        'ERASURE|YOU ARE NOT PART OF THE STORY. PLEASE LEAVE THE STORY.',
        'WICK|I think I am the point of the story.',
        'ERASURE|THAT IS NOT HOW POINTS WORK.',
        'LEDGER|They cannot erase what has already been written. Keep moving.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Ash hatches in the cinders of earlier Lamplighters.',
      script: [
        'In a heap of ash, an egg cracks. A chick made of tiny embers pokes out, yawns, and blinks.',
        'ASH|Oh. You are early. I was not ready. I am never ready. It is my favorite way to be.',
        'WICK|You are a phoenix?',
        'ASH|I am a fledgling. I have only ever known endings. They are very nice. You start with the bad part, and then it gets better.',
        'THISTLE|Ash, this is very dangerous.',
        'ASH|Everything is. I am coming with you.',
        { join: 'ash' },
        { give: 'plume', n: 1 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Archivist is fought. She closes the book. Wick dies and is reborn.',
      script: [
        'At the center of the page sits a long desk. Behind it, a pale woman in a Lamplighter\'s coat is writing with a pen that has no ink.',
        'ARCHIVIST|Hello, Ledger. You brought friends. You brought a seed. You brought an ending.',
        'LEDGER|Marrow, it is time.',
        'ARCHIVIST|No. No, it is not. I do not hear you, dear.',
        'WICK|Dawn would be three hundred years old, Marrow. She would not want this.',
        'ARCHIVIST|Do not say her name.',
        { battle: 0 },
        'Marrow sinks to her knees. The pen falls. Her face is very gentle and very tired.',
        'ARCHIVIST|I cannot let go. I do not know how. I am so sorry.',
        'She closes the book. It is a soft sound, like a door shutting on an empty room.',
        { flash: true },
        'Wick cannot feel his hands. Wick cannot feel the floor. The white is folding over him.',
        'WICK|...ah. So that is what it is like.',
        { card: ['...'] },
        'From the ash, a small warm voice: ASH|You are not finished. I will show you how it works.',
        'A flame rises. It catches the Seed in Wick\'s pocket and spills gold light through the page.',
        'ASH|There. Again.',
        'Wick gets up. His lantern is lit. It is a different light now: it flickers.',
        { give: 'starwater', n: 2 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'The party leaves the Margin. The Noon is flickering.',
      script: [
        'They walk out of the Margin. The white ripples as they go, like the surface of a pond.',
        'Above the page, the noon has a crack in it. A sliver of orange is leaking through.',
        'ARCHIVIST|...go. Tuck is waiting. It is still stuck. She cannot... I cannot...',
        'The voice fades. It sounds almost relieved.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Wick is not afraid of endings anymore.',
      script: [
        'Wick looks at his hands. They are the same hands. They are warm.',
        'WICK|I am not afraid of ending anymore.',
        'ASH|I know. It is a little bit funny, how much better it gets when you stop being.',
        'AJAR|I am still afraid.',
        'WICK|That is fine. You can be afraid and still open the door.',
        { card: ['END OF CHAPTER 11', 'The hero has died', 'and returned.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'blank', name: 'Blank Clerk', room: 2, lines: { 0: ['I am nobody. I am a blank. I am very good at this.'] } },
    { id: 'scribe', name: 'Half Scribe', room: 4, lines: { 0: ['I was about to write a sentence when the Noon came. It was going to be a good one.'] } },
    { id: 'spark', name: 'Spark', room: 5, lines: { 0: ['I am the last spark of a Lamplighter. I am warm. Please carry me.'] } },
    { id: 'sign', name: 'Sign', room: 3, lines: { 0: ['Written in light on the ground: THE END IS NOT A PLACE. IT IS A DIRECTION.'] } },
    { id: 'eraser', name: 'Eraser', room: 8, lines: { 0: ['I am an eraser. I am not here to remove you. I am here to be used, eventually, when it is time.'] } },
    { id: 'footnote', name: 'Footnote', room: 9, lines: { 0: ['A footnote on this page reads: see previous page. The previous page reads: see footnote.'] } },
  ],
  chests: [{ room: 3, give: 'starwater', n: 2 }, { room: 5, gold: 800 }, { room: 9, guard: ['hourhound'], give: 'r_nerve', n: 1 }],
};

export const CH12: ChapterDef = {
  id: 12, title: 'Evening', stage: 'Return with the Elixir', place: 'Tuck, at Last', seed: 1212, mech: 'dusk',
  theme: { name: 'noon', a: '#ffc83a', b: '#fff8d0', floor: 0, wall: 0, deco: ['candle', 'pillar', 'statue', 'crystal', 'flower'] },
  mechTitle: 'DUSK',
  mechText: ['Any hero can use DUSK on a foe under 35% HP.', 'Bosses can be ended under 18% HP.', 'Dusk is an ending given gently. It heals the party and fills NERVE.', 'Twice per battle.'],
  partymate: 'dusk',
  intro: ['CHAPTER 12', 'EVENING', '', 'Return with the Elixir'],
  beats: [
    {
      circle: 'you', room: 1, note: 'Tuck is frozen in its final noon.',
      script: [
        'Tuck is home, and Tuck is stuck. Every villager has frozen mid-step. The baker holds a loaf one inch from a cooling rack. Grommet stands with her mouth open on a word.',
        'WICK|We are back. Nobody moved.',
        'POCKET|I have never been so worried about a town holding still.',
        'The Lamp overhead is a very bright, very white disc.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need the evening. It has been hiding inside Sir Ajar.',
      script: [
        'LEDGER|Marrow loosened the noon, but it is still stuck. We need someone who can carry the dusk all the way to the Lamp.',
        'AJAR|There is someone. I have felt them behind my door for all these years. Wick. I am ready to open.',
        'WICK|Are you sure?',
        'AJAR|No. That is why I am doing it.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Sir Ajar opens his door. Dusk steps out.',
      script: [
        'Sir Ajar unlatches his chest. The hinges sing. Behind the door is a small, warm room with a window full of stars.',
        'DUSK|Hello. I am so sorry I am late.',
        'AJAR|You were in my armor the whole time?',
        'DUSK|I hid there when the Archivist exiled me. It was very cozy. Thank you for being an open door. You were so careful with me.',
        'WICK|You are the evening.',
        'DUSK|Yes. I have been the evening since before there was a morning. I am not very good at fighting. I am very good at endings. I think that will do.',
        { join: 'dusk' },
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'They climb the Belfry once more. Stay\'s echoes are waiting.',
      script: [
        'They climb the Belfry stairs. It looks smaller than they remember. The gearworks are silent. Every mite is frozen mid-chew.',
        'DUSK|It is very tense in here.',
        'Steps echo on the stairs ahead. The echoes of Stay hum softly, each holding a teacup.',
        'STAY|Please, please, please. One more noon. I am asking nicely.',
        'WICK|I know, Stay. I am sorry.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'At the Lamp, Marrow\'s grief is revealed as the Stopped Hour.',
      script: [
        'The Lamp hangs at the top of the Belfry. It is no longer brass. It is a single frozen second of light, shaped like a sleeping child.',
        'LAMP|Wick. You came. I asked for so little.',
        'WICK|I know. I am going to give it to you.',
        'LAMP|She is here. She has been here the whole time. Dawn is here, and Marrow is here, and they are so, so tired.',
        'THISTLE|Wick. Whatever you do, do it gently.',
        'Behind the Lamp, a huge and dazzling shape opens one great eye. It does not look angry. It looks frightened.',
      ],
    },
    {
      circle: 'take', room: 6, note: 'The last stand against Stay and the Stopped Hour.',
      script: [
        'The echoes of Stay form a ring between the party and the Lamp.',
        'STAY|I will not let you hurt her.',
        'WICK|I am not going to hurt her. I am going to let her go.',
        { battle: 0 },
        'The echoes collapse into cream-colored dust. A single teacup rolls to Wick\'s feet.',
        'STAY|...oh. I see. You are actually going to do it.',
        'Stay bows, gently, and is gone.',
        'Now the great eye above the Lamp opens fully. The Stopped Hour descends.',
        'DUSK|It is not a monster. It is a moment. It needs an ending, not a fight. But we have to get it low enough. Hit it. I will be there at the end.',
        { battle: 1 },
        'The Stopped Hour softens, blurs, and begins to hum. Dusk steps forward and lays a hand on it.',
        'DUSK|It is all right. It was a wonderful noon. You can rest.',
      ],
    },
    {
      circle: 'return', room: 7, note: 'Wick decides how the day ends.',
      script: [
        'The Stopped Hour holds still. In its glow, two faces: Marrow, and a small girl in a yellow hat.',
        'DAWN|Mama. I smiled. I remember it. It was a very good smile. Can we go home now?',
        'ARCHIVIST|Oh, my dear. I do not know how.',
        'DAWN|It is easy. You just stop holding it.',
        { choice: 'How does the day end?', opts: [
          { t: 'Let the evening come', do: [{ set: 'ending_dusk' }, 'WICK|Let it end. All of it. Gently.', 'The Lamp turns to a deep, tender orange.'] },
          { t: 'One last noon, then dusk', do: [{ set: 'ending_half' }, 'WICK|One last noon. Properly. With a sunset after.', 'The Lamp gleams gold, then turns, slowly, orange.'] },
        ] },
      ],
    },
    {
      circle: 'change', room: 1, note: 'The evening comes to Tuck. Wick winds the Lamp one last time to set.',
      script: [
        'The Lamp moves. Shadows stretch across the square, long and blue. Every villager yawns at once.',
        'GROMMET|...and that is why you never let the noon slip. Wait. Wick? What is that?',
        'WICK|It is an evening, Grommet. You said it made everyone quiet.',
        'GROMMET|I did not say that. Your gran did. She was right.',
        { if: 'ending_half', then: ['The villagers sit in the square for one long golden hour. Then the light goes orange, and everyone stays to watch.'], else: ['The villagers sit in the square and watch the orange light go down. Nobody says a word.'] },
        'POCKET|Dispensing the last thing I have. Peace. On the house.',
        'THISTLE|One more letter to deliver. It is addressed to the new night.',
        'DUSK|Good evening, everyone.',
        'Wick climbs the Belfry. The crank is a little stiff. He turns it a single time, to set.',
        { card: ['THE END', '', 'The Lamp sleeps.', 'The stars come out.', 'Somewhere a baker', 'is very confused.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'grommet', name: 'Grommet', room: 1, lines: { 0: ['...and that is why you never let the noon slip. (She is frozen mid-sentence.)'] } },
    { id: 'baker', name: 'Baker', room: 2, lines: { 0: ['(The baker is frozen holding a loaf. He looks pleased with it.)'] } },
    { id: 'child', name: 'Child', room: 3, lines: { 0: ['(A child is frozen with a stick poised over her shadow.)'] } },
    { id: 'sign', name: 'Sign', room: 4, lines: { 0: ['The Belfry sign, stuck in noon, reads: PLEASE DO NOT ENTER AFTER NOON. It is exactly as true as it used to be.'] } },
    { id: 'lamplit', name: 'Lamplit Mouse', room: 8, lines: { 0: ['It is very bright. I would love to blink. I have not blinked since noon, and I am beginning to feel it.'] } },
    { id: 'dawnbird', name: 'Dawn Bird', room: 9, lines: { 0: ['I am the last bird of the old dawn. I am learning to sing the evening. It is lower and sadder and I love it.'] } },
  ],
  chests: [{ room: 3, give: 'starwater', n: 3 }, { room: 5, gold: 1000 }, { room: 9, guard: ['archivist'], give: 'r_might', n: 1 }],
};
