import type { ChapterDef } from './types';

export const CH9: ChapterDef = {
  id: 9, title: 'The Null Garden', stage: 'Reward: Seizing the Sword', place: 'The Null Garden', seed: 909, mech: 'runes',
  theme: { name: 'garden', a: '#58b068', b: '#d8ff98', floor: 3, wall: 2, deco: ['tree', 'flower', 'statue', 'rock', 'pool'] },
  mechTitle: 'RUNES',
  mechText: ['Weapons and armor each have a rune socket.', 'Runes add effects like lifesteal, speed, or element power.', 'Equip them from the EQUIP menu. Runes are sold in shops.', 'Swap runes to suit the fight.'],
  partymate: 'fennel',
  intro: ['CHAPTER 9', 'THE NULL GARDEN'],
  beats: [
    {
      circle: 'you', room: 1, note: 'A garden where nothing grows or dies.',
      script: [
        'The hedges here are all cut to the same height. Every flower is open and every petal is whole. No bees.',
        'AJAR|It\'s lovely. Isn\'t it? Then why does my hinge hurt?',
        'THISTLE|Look at the gravel. Nobody has ever walked on it.',
        'KILN|No weeds. Not one. I\'d pay to see a weed.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'The Seed of Evening is hidden at the garden\'s heart.',
      script: [
        'LEDGER|The diary mentions two locks on the Margin door. We forged the key to one. The other takes a seed.',
        'WICK|What kind of seed?',
        'LEDGER|The Seed of Evening. Nothing dusk-colored can open unless it\'s planted first. She buried it deep, because she feared it most.',
        'ZUG|Buried it where nothing grows. Clever. Annoyingly clever. I\'d have done the same, three moves back.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'They enter the hedge maze.',
      script: [
        'The maze has no paths. Only gaps where a hedge would be if anyone had planted one.',
        'ROUTE 9|Next stop, nowhere in particular. I can drive through all of it, but it\'s so tidy. I don\'t want to leave tire marks.',
        'POCKET|Left. Right. Left again. I\'m inventing this route as I go, and I\'m loving it.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'They find a gardener who prunes in secret.',
      script: [
        'Behind a hedge, someone in a straw hat is sawing at a rosebush. Very slowly. Very quietly.',
        'FENNEL|Shh. Please. If she hears the saw, she\'ll...nothing here is meant to change, you see. Nothing at all.',
        'WICK|Then why are you cutting?',
        'FENNEL|A rose that never wilts never gets to finish. So I trim a little off the edges. Now and then. So the edges remember they\'re edges.',
        'KILN|Huh. I like this one.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Fennel shows the one bud close to blooming. The Seed of Evening.',
      script: [
        'Fennel leads them to a clearing. A pot sits in the middle with one tight bud in it, the color of a late sunset.',
        'FENNEL|Three hundred years I\'ve watered this. It tries to open every spring, and every spring the Garden presses it shut again.',
        'WICK|That\'s the Seed of Evening.',
        'FENNEL|Mm. And if it opens, the Garden ends. I\'ve been hoping for that and dreading it, both, for so long my hands shake. Could I come along? If it\'s allowed?',
        'WICK|It is.',
        { join: 'fennel' },
        { give: 'r_ember', n: 1 },
        { give: 'r_siphon', n: 1 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Evergreen guards the bud. They prune it.',
      script: [
        'The hedge wall bulges. A tree made of ruler-straight trunks hauls itself out of it.',
        'EVERGREEN|I AM NEVER FINISHED. I AM NEVER DEAD. I AM THE GARDEN. STAND BACK FROM THE BUD.',
        'FENNEL|I\'m sorry. You\'re beautiful, truly. But you\'re standing in the way.',
        { battle: 0 },
        'The tree shudders. One brown leaf drops from its crown, the first in three hundred years.',
        'Back in the clearing, the bud swells and splits open. The Seed of Evening is a small, sleepy, orange star.',
        { give: 'starwater', n: 1 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'Stay ambushes them on the way out.',
      script: [
        'The Garden browns at its edges. Petals drift down, slow as snow.',
        'STAY|Oh no. Oh no, no. What did you do? It was so nice here.',
        'STAY|Please. Put it back. Please.',
        'WICK|I can\'t, Stay. It was never yours to keep.',
        'STAY|Then I\'ll have to ask a bit more firmly.',
        { fight: ['stayecho', 'noonshade'] },
        'The echoes of Stay thin out and fade. The real one is nowhere. A teacup lies in pieces in the grass.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'The bud blooms for the first time.',
      script: [
        'The Seed sits in Wick\'s palm, warm as a coal. A thin orange glow leaks from it and pools along the edge of the sky.',
        'FENNEL|Oh. There it is. I had it wrong. The painting was nothing like this.',
        'THISTLE|Wick. Your face is wet.',
        'WICK|Yeah. Good wet, though.',
        { card: ['END OF CHAPTER 9', 'A seed, warm as a coal,', 'in Wick\'s palm.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'gnome', name: 'Garden Gnome', room: 2, lines: { 0: ['Don\'t pick anything. Don\'t water anything. And keep your voice down near the roses, they get ideas.'], 7: ['A leaf fell! Over by the pond! Somebody sweep it up before she notices!'] } },
    { id: 'bee', name: 'Lone Bee', room: 3, lines: { 0: ['Bzz. Last bee here. Every flower\'s already open, so I just hover. Wave at me, would you? Somebody should.'] } },
    { id: 'scarecrow', name: 'Scarecrow', room: 5, lines: { 0: ['Not one crow in three hundred years. Folks keep saying I\'m doing a great job. I\'d like to see one crow, just to check.'] } },
    { id: 'sign', name: 'Sign', room: 4, lines: { 0: ['A sign reads: PLEASE DO NOT WATER THE FLOWERS. THEY HAVE BEEN PERFECT SINCE BEFORE YOU WERE BORN.'] } },
    { id: 'snail', name: 'Garden Snail', room: 8, lines: { 0: ['Slowest thing in the garden, me. Lately I\'m also the only thing that\'s gotten anywhere. Go figure.'] } },
    { id: 'seedsaver', name: 'Seed Saver', room: 9, lines: { 0: ['Everything in these jars is saved for later. Later\'s been a long time coming. I\'ve started writing SOON on the labels.'] } },
  ],
  chests: [{ room: 3, give: 'ink3', n: 1 }, { room: 5, gold: 500 }, { room: 9, guard: ['overdue'], give: 'r_bulwark', n: 1 }, { room: 9, give: 'r_quick', n: 1 }],
};

export const CH10: ChapterDef = {
  id: 10, title: 'The Unraveling', stage: 'The Road Back', place: 'The Seams', seed: 1010, mech: 'rewind',
  theme: { name: 'seams', a: '#ff7aa8', b: '#8ac8ff', floor: 1, wall: 1, deco: ['cog', 'web', 'crystal', 'rock', 'flower'] },
  mechTitle: 'REWIND',
  mechText: ['Once per battle you may REWIND.', 'Time folds back to the previous hero\'s turn and everything since is reshuffled.', 'Enemy attacks are re-rolled.', 'Use it after a bad turn.'],
  partymate: 'tick',
  intro: ['CHAPTER 10', 'THE UNRAVELING'],
  beats: [
    {
      circle: 'you', room: 1, note: 'The quilt is unpicking behind them.',
      script: [
        'The Garden frays. Threads peel off the hedges and rise into the sky in one long pink ribbon.',
        'LEDGER|She knows. Marrow is pulling the Seams loose to stop us, and the way we came is coming apart.',
        'ROUTE 9|Then hold on. Express service, no stops.',
        'Behind them, a horn sounds. Low and hollow and hungry.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need someone who can move through time itself.',
      script: [
        'FENNEL|Hounds of Hours. They go after anything that\'s out of step.',
        'ZUG|We\'re out of step by definition. Options?',
        'THISTLE|There\'s a rabbit out here who slips between the ticks. Everyone on the Seams knows him. He\'s always early.',
        'WICK|Early for what?',
        'THISTLE|That\'s the trouble. He\'s never on time either.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'They sprint onto the thread road.',
      script: [
        'The road is a single red thread, pulled tight over nothing at all.',
        'POCKET|For the record, I\'d like a refund on this entire road.',
        'WICK|Noted. Run.',
        { unlock: true },
        'Behind them the ground unpicks itself with a long, ripping sigh.',
      ],
    },
    {
      circle: 'search', room: 4, note: 'They find a clock with a missing minute hand.',
      script: [
        'A grandfather clock stands in the middle of the road with no hands on it. A clockwork rabbit circles it, wringing his paws.',
        'TICK|Early! Late! Both! Where\'s my minute hand, where\'s my minute hand?',
        'WICK|Hi. Are you Tick?',
        'TICK|Yes! I was here yesterday, which is today, which is three hundred years ago. Stuck at eleven fifty nine, the whole time, every time.',
        'TICK|The Hound took my minute hand. Get it back and I\'ll show you how to fold a moment. Quick, quick.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'They find the stolen minute hand. Tick joins.',
      script: [
        'The minute hand is wedged in a nest of threads. It\'s still ticking and it looks mildly irritated.',
        'TICK|There it is! Oh, I can feel the seconds again! Hello, seconds. Hello, hello.',
        'TICK|Right, here\'s how it works. Make a bad move and you can take one moment back. Just one. Only if everyone in it agrees, mind.',
        'WICK|Will they?',
        'TICK|They\'re your friends. Friends say yes to that sort of thing.',
        { join: 'tick' },
        { give: 'feather', n: 2 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Hound of Hours is fought and turned aside.',
      script: [
        'The horn is right behind them now. A hound built from silver minute hands and clock faces lopes out of the thread-fog.',
        'HOUND|LATE. LATE. LATE. EVERYONE IS ALWAYS LATE.',
        'TICK|Not me. I\'m early. And I\'ve got a very good excuse.',
        { battle: 0 },
        'The Hound whimpers. Its clock faces go soft, and it curls up in a heap of quietly ticking silver.',
        'WICK|Good dog. Poor, tired dog.',
        { give: 'flask', n: 2 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'They reach the Margin door at the edge of the world.',
      script: [
        'The thread road ends at a door with no wall around it. It stands taller than a cathedral, shaped like a blank page.',
        'LEDGER|The Margin.',
        'ZUG|I expected more fanfare.',
        'Somewhere past the door, something very old lets out a breath.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Tick\'s clock finally moves to twelve.',
      script: [
        'Something clicks in Tick\'s chest. The little clockwork hand lifts off eleven fifty nine.',
        'TICK|It\'s moving. It\'s twelve. Noon, actual noon. Listen to it go!',
        'WICK|It\'s always been noon.',
        'TICK|Not like this. This one\'s going somewhere.',
        { card: ['END OF CHAPTER 10', 'A door taller than', 'a cathedral.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'spool', name: 'Spool', room: 2, lines: { 0: ['I\'ve been holding this thread since the sewing. Won\'t let go, either, not till somebody tells me it\'s safe. Nobody\'s told me.'] } },
    { id: 'button', name: 'Loose Button', room: 3, lines: { 0: ['Fell off a coat three hundred years back. The coat\'s long gone, but I keep my eyes out for the right buttonhole.'], 6: ['Hey! Can anyone here sew? Anyone? Please?'] } },
    { id: 'snip', name: 'Old Needle', room: 5, lines: { 0: ['Sharp as ever, and nobody\'s asked. Haven\'t pricked a soul in decades. I\'d like to get back to work, if you hear of any.'] } },
    { id: 'sign', name: 'Sign', room: 4, lines: { 0: ['A sign reads: PLEASE KEEP FEET OFF THE THREAD. IT IS THE ONLY THING HOLDING THE WORLD TOGETHER.'] } },
    { id: 'thimble', name: 'Thimble', room: 8, lines: { 0: ['A giant wore me once. Then she left, and I stayed. Somebody\'s got to guard the finger.'] } },
    { id: 'patch', name: 'Patch', room: 9, lines: { 0: ['I\'m a patch. I hold things shut, and right now I\'m holding awfully hard. Is that a needle? Is it yours?'] } },
  ],
  chests: [{ room: 3, give: 'ink3', n: 1 }, { room: 5, gold: 600 }, { room: 9, guard: ['evergreen'], give: 'r_edge', n: 1 }],
};

export const CH11: ChapterDef = {
  id: 11, title: 'The Last Page', stage: 'Resurrection', place: 'The Margin', seed: 1111, mech: 'ascend',
  theme: { name: 'margin', a: '#a0a0b8', b: '#ffffff', floor: 3, wall: 3, deco: ['moon', 'pillar', 'crystal', 'statue', 'rock'] },
  mechTitle: 'ASCENSION AND REBIRTH',
  mechText: ['At full NERVE you may ASCEND instead of using LIMIT.', 'Ascended heroes gain 30% ATK, MAG, SPD and cast free for four turns.', 'In boss fights, a wiped party is REBORN once at half HP with full NERVE.', 'Dying is only a setback.'],
  partymate: 'ash',
  intro: ['CHAPTER 11', 'THE LAST PAGE'],
  beats: [
    {
      circle: 'you', room: 1, note: 'The party steps into blank white.',
      script: [
        'Past the door there is no floor. There is only white, ruled with faint writing lines.',
        'AMPERE|A page! We stand upon a page! I can feel the grain of the paper!',
        'POCKET|It\'s a very big page. Nothing\'s printed on it. I checked the whole thing for a price.',
        'FENNEL|This is where she keeps what hasn\'t been written yet.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They must confront Marrow Vale.',
      script: [
        'LEDGER|We have the key and we have the seed. That leaves Marrow.',
        'THISTLE|She won\'t want to hear it.',
        'LEDGER|No. But I wrote the contract, so I\'ll read her the terms myself.',
        'Somewhere ahead a pen scratches. It doesn\'t stop for breath.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'They step onto the page.',
      script: [
        'They cross the white. Where they step, black letters appear underfoot: ROUTE 9 WALKED. KILN WALKED. TICK WALKED.',
        'TICK|Somebody\'s writing me down! Stop writing me down!',
        'WICK|Stay close. Don\'t read ahead.',
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'Redactions and erasures stand between them and the author.',
      script: [
        'Black bars and pale, faceless angels drift along the margins. They look each of the party over, one at a time, and reach out to smudge.',
        'ERASURE|YOU ARE NOT IN THE STORY. PLEASE LEAVE THE STORY.',
        'WICK|I think I\'m what it\'s about, actually.',
        'ERASURE|THAT IS NOT HOW IT WORKS.',
        'LEDGER|They can\'t strike out what\'s already inked. Keep walking.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'Ash hatches in the cinders of earlier Lamplighters.',
      script: [
        'In a heap of old ash, an egg cracks. A chick made of tiny embers pokes its head out, yawns, and blinks at them.',
        'ASH|Oh! You\'re early. I wasn\'t ready. I never am, it\'s my favorite way to be.',
        'WICK|You\'re a phoenix?',
        'ASH|Fledgling. Endings are all I\'ve ever seen, and honestly, they\'re great. Bad part first, then it gets better.',
        'THISTLE|Ash, where we\'re going is dangerous.',
        'ASH|Everywhere is. I\'m coming.',
        { join: 'ash' },
        { give: 'plume', n: 1 },
      ],
    },
    {
      circle: 'take', room: 6, note: 'The Archivist is fought. She closes the book. Wick dies and is reborn.',
      script: [
        'A long desk sits at the center of the page. Behind it, a pale woman in a Lamplighter\'s coat writes with a pen that has no ink.',
        'ARCHIVIST|Ledger. You brought friends. And a seed. You brought me an ending, didn\'t you.',
        'LEDGER|Marrow, it\'s time.',
        'ARCHIVIST|No. I don\'t hear you, dear. I\'m busy.',
        'WICK|Dawn would be three hundred years old, Marrow. She wouldn\'t want this.',
        'ARCHIVIST|Don\'t say her name.',
        { battle: 0 },
        'Marrow sinks to her knees. The pen falls. Her face is gentle, and so tired.',
        'ARCHIVIST|I can\'t let go. I don\'t know how. I\'m sorry. I\'m so sorry.',
        'She closes the book. It makes a soft sound, like a door shutting on an empty room.',
        { flash: true },
        'Wick can\'t feel his hands. He can\'t feel the floor. The white folds over him.',
        'WICK|...ah. So that\'s what it\'s like.',
        { card: ['...'] },
        'From somewhere in the dark, a small warm voice.',
        'ASH|Not finished. Not yet. Watch, it\'s easy.',
        'A flame rises. It catches the Seed in Wick\'s pocket and spills gold light across the page.',
        'ASH|There. Again.',
        'Wick gets up. His lantern is lit, but the light is different now. It flickers.',
        { give: 'starwater', n: 2 },
      ],
    },
    {
      circle: 'return', room: 7, note: 'The party leaves the Margin. The Noon is flickering.',
      script: [
        'They walk out of the Margin. The white ripples behind them like the surface of a pond.',
        'Above the page, the noon has a crack in it. A sliver of orange leaks through.',
        'ARCHIVIST|...go. Tuck is waiting. It\'s still stuck. I couldn\'t...I can\'t...',
        'Her voice fades. It sounds almost relieved.',
      ],
    },
    {
      circle: 'change', room: 1, note: 'Wick is not afraid of endings anymore.',
      script: [
        'Wick turns his hands over. Same hands. Warm.',
        'WICK|I keep waiting to be scared.',
        'ASH|Funny, isn\'t it? It gets lighter once you stop.',
        'AJAR|I\'m still scared. A little.',
        'WICK|Good. Open the door anyway.',
        { card: ['END OF CHAPTER 11', 'Wick\'s lantern', 'now flickers.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'blank', name: 'Blank Clerk', room: 2, lines: { 0: ['Name? I don\'t have one. Neither does anybody here. It\'s easier on the filing.'] } },
    { id: 'scribe', name: 'Half Scribe', room: 4, lines: { 0: ['I\'d just started a sentence when the Noon came. Good one, too. Something about a river. I never got to the river.'] } },
    { id: 'spark', name: 'Spark', room: 5, lines: { 0: ['I\'m what\'s left of a Lamplighter. Warm, mostly. Would you carry me a while? I don\'t weigh much.'] } },
    { id: 'sign', name: 'Sign', room: 3, lines: { 0: ['Written in light on the ground: THE END IS NOT A PLACE. IT IS A DIRECTION.'] } },
    { id: 'eraser', name: 'Eraser', room: 8, lines: { 0: ['Don\'t worry, I\'m not here for you. I\'m here for later. When somebody finally says it\'s time, I\'ll be ready.'] } },
    { id: 'footnote', name: 'Footnote', room: 9, lines: { 0: ['A footnote on this page reads: see previous page. The previous page reads: see footnote.'] } },
  ],
  chests: [{ room: 3, give: 'starwater', n: 2 }, { room: 5, gold: 800 }, { room: 9, guard: ['hourhound'], give: 'r_nerve', n: 1 }],
};

export const CH12: ChapterDef = {
  id: 12, title: 'Evening', stage: 'Return with the Elixir', place: 'Tuck, at Last', seed: 1212, mech: 'dusk',
  theme: { name: 'noon', a: '#ffc83a', b: '#fff8d0', floor: 0, wall: 0, deco: ['candle', 'pillar', 'statue', 'crystal', 'flower'] },
  mechTitle: 'DUSK',
  mechText: ['Any hero can use DUSK on a foe under 35% HP.', 'Bosses can be ended under 18% HP.', 'Dusk is an ending given gently. It heals the party and fills NERVE.', 'Twice per battle.'],
  partymate: 'dusk',
  intro: ['CHAPTER 12', 'EVENING'],
  beats: [
    {
      circle: 'you', room: 1, note: 'Tuck is frozen in its final noon.',
      script: [
        'Tuck is home, and Tuck is stuck. Every villager is frozen mid-step. The baker holds a loaf an inch above the cooling rack. Grommet has her mouth open on a word.',
        'WICK|Nobody\'s moved.',
        'POCKET|I\'ve never been this nervous about a town standing still.',
        'Overhead, the Lamp is a hard white disc.',
      ],
    },
    {
      circle: 'need', room: 2, note: 'They need the evening. It has been hiding inside Sir Ajar.',
      script: [
        'LEDGER|Marrow loosened the noon, but it\'s still jammed. Someone has to carry the dusk the whole way up to the Lamp.',
        'AJAR|Someone can. I\'ve felt them behind my door for years now. Wick, I\'m ready to open.',
        'WICK|Are you sure?',
        'AJAR|No. I\'m doing it anyway.',
      ],
    },
    {
      circle: 'go', room: 3, note: 'Sir Ajar opens his door. Dusk steps out.',
      script: [
        'Sir Ajar unlatches his chest. The hinges sing. Behind the door is a small warm room with a window full of stars.',
        'DUSK|Hello. I\'m sorry I\'m late. I came as fast as I could.',
        'AJAR|You were in my armor? All this time?',
        'DUSK|When she sent me away, I hid in here. It was cozy. You kept the door so carefully shut. Thank you.',
        'WICK|You\'re the evening.',
        'DUSK|I was the evening before there was a morning. I\'m not much of a fighter. I\'m rather good at endings, though. I think that will do.',
        { join: 'dusk' },
        { unlock: true },
      ],
    },
    {
      circle: 'search', room: 4, note: 'They climb the Belfry once more. Stay\'s echoes are waiting.',
      script: [
        'They climb the Belfry stairs. The tower seems smaller than before. The gears sit silent and every mite is frozen mid-chew.',
        'DUSK|It\'s very tense in here. Someone\'s holding their breath.',
        'Footsteps echo on the stairs above. The echoes of Stay hum together, each holding a teacup.',
        'STAY|Please, please, please. One more noon. I\'m asking nicely.',
        'WICK|I know, Stay. I\'m sorry.',
      ],
    },
    {
      circle: 'find', room: 5, note: 'At the Lamp, Marrow\'s grief is revealed as the Stopped Hour.',
      script: [
        'The Lamp hangs at the top of the Belfry. It\'s no longer brass. It\'s one frozen second of light, shaped like a sleeping child.',
        'LAMP|Wick. You came. All I asked for was a little.',
        'WICK|I know. I\'m going to give you something better.',
        'LAMP|She\'s in here. Dawn\'s here, and Marrow\'s here, and they\'re both so tired.',
        'THISTLE|Wick. Whatever you do, do it softly.',
        'Behind the Lamp, a huge dazzling shape opens one great eye. It doesn\'t look angry. It looks frightened.',
      ],
    },
    {
      circle: 'take', room: 6, note: 'The last stand against Stay and the Stopped Hour.',
      script: [
        'The echoes of Stay form a ring between the party and the Lamp.',
        'STAY|I won\'t let you hurt her.',
        'WICK|I\'m not going to hurt her. I\'m going to let her go.',
        { battle: 0 },
        'The echoes crumble into cream-colored dust. One teacup rolls to Wick\'s feet.',
        'STAY|...oh. You mean it. You\'re really going to do it.',
        'Stay bows, gently, and is gone.',
        'Above the Lamp, the great eye opens all the way. The Stopped Hour descends.',
        'DUSK|It isn\'t a monster. It\'s a single moment, and moments want endings. But we have to wear it down first. Hit it. I\'ll be there at the end.',
        { battle: 1 },
        'The Stopped Hour softens and blurs and starts to hum. Dusk steps forward and lays a hand on it.',
        'DUSK|There now. It was a lovely noon. You can rest.',
      ],
    },
    {
      circle: 'return', room: 7, note: 'Wick decides how the day ends.',
      script: [
        'The Stopped Hour holds still. In its glow there are two faces. Marrow, and a small girl in a yellow hat.',
        'DAWN|Mama. I smiled. Do you remember? It was a good one. Can we go home now?',
        'ARCHIVIST|Oh, love. I don\'t know how.',
        'DAWN|Just open your hands.',
        { choice: 'How does the day end?', opts: [
          { t: 'Let the evening come', do: [{ set: 'ending_dusk' }, 'WICK|Let it end. All of it, gently.', 'The Lamp turns a deep, tender orange.'] },
          { t: 'One last noon, then dusk', do: [{ set: 'ending_half' }, 'WICK|One last noon first. A real one. Then the sunset.', 'The Lamp gleams gold, then slowly turns orange.'] },
        ] },
      ],
    },
    {
      circle: 'change', room: 1, note: 'The evening comes to Tuck. Wick winds the Lamp one last time to set.',
      script: [
        'The Lamp moves. Long blue shadows stretch across the square. Every villager yawns at once.',
        'GROMMET|...and that\'s why you never let the noon slip. Wait. Wick? What\'s that on the cobbles?',
        'WICK|Evening, Grommet. You said it makes everyone go quiet.',
        'GROMMET|I never said that. Your gran did. She was right.',
        { if: 'ending_half', then: ['The villagers sit in the square for one long golden hour. Then the light goes orange, and everyone stays to watch.'], else: ['The villagers sit in the square and watch the orange light go down. Nobody says a word.'] },
        'POCKET|Last item in stock. Peace and quiet. On the house.',
        'THISTLE|One more letter to deliver. It\'s addressed to the new night.',
        'DUSK|Good evening, everyone.',
        'Wick climbs the Belfry. The crank is a little stiff. He turns it once, to set.',
        { card: ['THE END', '', 'The Lamp sleeps.', 'The stars come out.', 'Somewhere a baker', 'is very confused.'] },
        { end: true },
      ],
    },
  ],
  npcs: [
    { id: 'grommet', name: 'Grommet', room: 1, lines: { 0: ['...and that is why you never let the noon slip. (She is frozen mid-sentence.)'] } },
    { id: 'baker', name: 'Baker', room: 2, lines: { 0: ['(The baker is frozen holding a loaf. He looks pleased with it.)'] } },
    { id: 'child', name: 'Child', room: 3, lines: { 0: ['(A child is frozen with a stick poised over her shadow.)'] } },
    { id: 'sign', name: 'Sign', room: 4, lines: { 0: ['The Belfry sign, stuck in noon, reads: PLEASE DO NOT ENTER AFTER NOON. It is exactly as true as it used to be.'] } },
    { id: 'lamplit', name: 'Lamplit Mouse', room: 8, lines: { 0: ['Too bright in here. All I want is to blink. Haven\'t since noon, and my eyes are starting to sting.'] } },
    { id: 'dawnbird', name: 'Dawn Bird', room: 9, lines: { 0: ['Last bird of the old dawn, that\'s me. Learning the evening song now. It sits lower and sadder, and I love it more than the old one.'] } },
  ],
  chests: [{ room: 3, give: 'starwater', n: 3 }, { room: 5, gold: 1000 }, { room: 9, guard: ['archivist'], give: 'r_might', n: 1 }],
};
